force-app/main/default/objects/ERUM_Direcciones_Envio__c/ERUM_Direcciones_Envio__c.object-meta.xml
<CustomObject>
    <label>Direcciones Envio</label>
    <nameField>
        <label>Nombre Dirección</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direcciones Envio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Gestion_de_errores__c/Gestion_de_errores__c.object-meta.xml
<CustomObject>
    <label>Gestión de errores</label>
    <nameField>
        <displayFormat>ErrorNo - {00000000}</displayFormat>
        <label>Error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gestiones de errores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gestion_de_errores__c/fields/Codigo_de_error__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_error__c</fullName>
    <label>Código de error</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gestion_de_errores__c/fields/Codigo_Navision__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Navision__c</fullName>
    <label>Código Navision</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gestion_de_errores__c/fields/Codigo_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Salesforce__c</fullName>
    <label>Código Salesforce</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gestion_de_errores__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Gestiones de errores</relationshipLabel>
    <relationshipName>Gestiones_de_errores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gestion_de_errores__c/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dirección</label>
    <referenceTo>ERUM_Direcciones_Envio__c</referenceTo>
    <relationshipLabel>Gestiones de errores</relationshipLabel>
    <relationshipName>Gestiones_de_errores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gestion_de_errores__c/fields/Fecha_y_hora__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_hora__c</fullName>
    <label>Fecha y hora</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Gestion_de_errores__c/fields/Integracion_fallida__c.field-meta.xml
<CustomField>
    <fullName>Integracion_fallida__c</fullName>
    <label>Integración fallida</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Productos</fullName>
            </value>
            <value>
                <fullName>Tarifas</fullName>
            </value>
            <value>
                <fullName>Clientes</fullName>
            </value>
            <value>
                <fullName>Direcciones</fullName>
            </value>
            <value>
                <fullName>Pedidos</fullName>
            </value>
            <value>
                <fullName>Líneas de Pedido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gestion_de_errores__c/fields/Origen__c.field-meta.xml
<CustomField>
    <fullName>Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Navision</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gestion_de_errores__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Gestiones de errores</relationshipLabel>
    <relationshipName>Gestiones_de_errores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gestion_de_errores__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Gestiones de errores</relationshipLabel>
    <relationshipName>Gestiones_de_errores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gestion_de_errores__c/fields/Tarifa__c.field-meta.xml
<CustomField>
    <fullName>Tarifa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tarifa</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Gestiones de errores</relationshipLabel>
    <relationshipName>Gestiones_de_errores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Pedido.recordType-meta.xml
<RecordType>
    <fullName>Pedido</fullName>
    <active>true</active>
    <businessProcess>Pedido</businessProcess>
    <label>Pedido</label>
</RecordType>

force-app/main/default/classes/GestionErrores.cls
public with sharing class GestionErrores {
    
    public static void insertGestionErrores(String error, String origen, Integer codigoError, String codigoSalesforce, String codigoNavision, String integracion) {
        
        Gestion_de_errores__c gestion = new Gestion_de_errores__c(
            Descripcion__c = error, 
            Fecha_y_hora__c = System.now(), 
            Origen__c = origen, 
            Codigo_de_error__c = codigoError, 
            Codigo_Salesforce__c = codigoSalesforce, 
            Codigo_Navision__c = codigoNavision, 
            Integracion_fallida__c = integracion
        );

        if (String.isNotBlank(gestion.Codigo_Salesforce__c) && String.isNotBlank(gestion.Integracion_fallida__c)) {
            try {
                switch on gestion.Integracion_fallida__c {
                    when 'Clientes' {
                        gestion.Cuenta__c = [SELECT Id FROM Account WHERE Id =: gestion.Codigo_Salesforce__c LIMIT 1].Id;
                    }
                    when 'Direcciones' {
                        gestion.Direccion__c = [SELECT Id FROM ERUM_Direcciones_Envio__c WHERE Id =: gestion.Codigo_Salesforce__c LIMIT 1].Id;
                    }
                    when 'Pedidos' {
                        gestion.Pedido__c = [SELECT Id FROM Opportunity WHERE Id =: gestion.Codigo_Salesforce__c LIMIT 1].Id;
                    } when 'Líneas de Pedido' {
                        gestion.Pedido__c = [SELECT Id FROM Opportunity WHERE Id =: gestion.Codigo_Salesforce__c LIMIT 1].Id;
                    }
                    when else {
                        return;
                    }
                }
            } catch (QueryException qEx) {
                System.debug('Error al crear el objeto de gestión de errores. No se ha podido encontrar ninguna coincidencia para el registro de tipo ' + gestion.Integracion_fallida__c + ' con id ' + gestion.Codigo_Salesforce__c + '.');
            }
        } 
        
        else if(String.isNotBlank(gestion.Codigo_Navision__c) && String.isNotBlank(gestion.Integracion_fallida__c)) {
            try {
                switch on gestion.Integracion_fallida__c {
                    when 'Productos' {
                        gestion.Producto__c = [SELECT Id FROM Product2 WHERE Id =: gestion.Codigo_Navision__c LIMIT 1].Id;
                    }
                    when 'Tarifas' {
                        gestion.Tarifa__c = [SELECT Id FROM Pricebook2 WHERE Id =: gestion.Codigo_Navision__c LIMIT 1].Id;
                    }
                    when else {
                        return;
                    }
                }
            } catch (QueryException qEx) {
                System.debug('Error al crear el objeto de gestión de errores. No se ha podido encontrar ninguna coincidencia para el registro de tipo ' + gestion.Integracion_fallida__c + ' con id ' + gestion.Codigo_Salesforce__c + '.');
            }
        }

        try {
            Database.insert(gestion, true);
        } catch (DmlException dmlEx2) {
            System.debug('Error al crear el objeto de gestión de errores. Detalles de la excepción: ' + dmlEx2.getMessage());
        }
        
    }
}