force-app/main/default/objects/Pricebook2/fields/ERUM_Fecha_Inicio__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Inicio__c</fullName>
    <label>Fecha Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/ERUM_Moneda__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Moneda__c</fullName>
    <label>Moneda</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/ERUM_PB_Id_External__c.field-meta.xml
<CustomField>
    <fullName>ERUM_PB_Id_External__c</fullName>
    <externalId>true</externalId>
    <label>PB Id External</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/C_d_Unidad_de_medida__c.field-meta.xml
<CustomField>
    <fullName>C_d_Unidad_de_medida__c</fullName>
    <label>Cód.Unidad medida</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAJA</fullName>
            </value>
            <value>
                <fullName>CAPA</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>PALLET</fullName>
            </value>
            <value>
                <fullName>PCS.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Codigo_de_ventas__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Codigo_de_ventas__c</fullName>
    <label>Código de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Fecha_Final__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Final__c</fullName>
    <label>Fecha Final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Fecha_Inicial__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Inicial__c</fullName>
    <label>Fecha Inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Incluir_coste_contenedor__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Incluir_coste_contenedor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incluir coste contenedor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Nombre_codigo_de_ventas__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Nombre_codigo_de_ventas__c</fullName>
    <label>Nombre código de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Tipo_de_venta__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_de_venta__c</fullName>
    <label>Tipo de venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Grupo precio cliente</fullName>
            </value>
            <value>
                <fullName>Todos los clientes</fullName>
            </value>
            <value>
                <fullName>Campaña</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Id_LineaTarifa__c.field-meta.xml
<CustomField>
    <fullName>Id_LineaTarifa__c</fullName>
    <externalId>true</externalId>
    <label>Id Línea de Tarifa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Alto_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Alto_embalaje__c</fullName>
    <label>Alto embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Ancho_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Ancho_embalaje__c</fullName>
    <label>Ancho embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Ancho_pala__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Ancho_pala__c</fullName>
    <label>Ancho pala</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Bloqueado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Bloqueado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bloqueado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cantidad_por_palet__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cantidad_por_palet__c</fullName>
    <label>Cantidad por palet</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cod_categoria_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cod_categoria_producto__c</fullName>
    <label>Cód.categoría producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cod_categoria_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cod_grupo_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cod_grupo_producto__c</fullName>
    <label>Cód. grupo producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cod_grupo_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Enviada_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Enviada_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviada ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_External_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ERUM_External_ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>Código Producto BC</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_contable_inventario__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_contable_inventario__c</fullName>
    <label>Grupo contable inventario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_inventario</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_contable_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_contable_producto__c</fullName>
    <label>Grupo contable producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_prod_Servicio__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_prod_Servicio__c</fullName>
    <label>Grupo prod. Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_prod_Servicio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_registro_IVA_prod__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_registro_IVA_prod__c</fullName>
    <label>Grupo registro IVA prod.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_registro_IVA_prod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Largo_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Largo_embalaje__c</fullName>
    <label>Largo embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Material_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Material_producto__c</fullName>
    <label>Material producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Media_percha__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Media_percha__c</fullName>
    <label>Media percha</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Nivel_tecnoligico__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Nivel_tecnoligico__c</fullName>
    <label>Nivel tecnológico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procede</fullName>
            </value>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_bruto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_bruto__c</fullName>
    <label>Peso bruto</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_bruto_cantidad_embalada__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_bruto_cantidad_embalada__c</fullName>
    <label>Peso bruto cantidad embalada</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_embalaje__c</fullName>
    <label>Peso embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_neto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_neto__c</fullName>
    <label>Peso neto</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_neto_cantidad_embalada__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_neto_cantidad_embalada__c</fullName>
    <label>Peso neto cantidad embalada</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Stock_disponible__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Stock_disponible__c</fullName>
    <inlineHelpText>Recuerde actualizar la página al consultar el Stock, tras 30 segundos, pulsando: &quot;ctrl&quot; + &quot;F5&quot;.</inlineHelpText>
    <label>Stock disponible</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventario</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_de_materia_prima__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_de_materia_prima__c</fullName>
    <label>Tipo de materia prima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procede</fullName>
            </value>
            <value>
                <fullName>Virgen</fullName>
            </value>
            <value>
                <fullName>Reciclado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_de_material__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_de_material__c</fullName>
    <label>Tipo de material</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_palet__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_palet__c</fullName>
    <label>Tipo palet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Europeo</fullName>
            </value>
            <value>
                <fullName>Americano</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Unidad_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Unidad_embalaje__c</fullName>
    <label>Unidad embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Volumen__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Volumen__c</fullName>
    <label>Volumen</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Volumen_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Volumen_embalaje__c</fullName>
    <label>Volumen embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_envio_ERP__c.field-meta.xml
<CustomField>
    <fullName>Fecha_envio_ERP__c</fullName>
    <label>Fecha envío ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Cod_categoria_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALMACEN</fullName>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
        <label>COMPLEMENTOS MADERA</label>
    </customValue>
    <customValue>
        <fullName>CP</fullName>
        <label>COMPLEMENTOS PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>MLD02549</fullName>
        <label>CRF06 30</label>
    </customValue>
    <customValue>
        <fullName>MPM</fullName>
        <label>MATERIA PRIMA MADERA</label>
    </customValue>
    <customValue>
        <fullName>MPP</fullName>
        <label>MATERIA PRIMA PLÁSTICOMATERIA PRIMA PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>PIM</fullName>
        <label>PRODUCTO INTERMEDIO MADERA</label>
    </customValue>
    <customValue>
        <fullName>PIP</fullName>
        <label>PRODUCTO INTERMEDIO PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>PTM</fullName>
        <label>PRODUCTO TERMINADO MADERA</label>
    </customValue>
    <customValue>
        <fullName>PTP</fullName>
        <label>PRODUCTO TERMINADO PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>SIN</fullName>
        <label>SIN CLASIFICACION</label>
    </customValue>
    <masterLabel>Cód. categoría producto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_inventario.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ENVASES</fullName>
        <label>Envases y embalajes</label>
    </customValue>
    <customValue>
        <fullName>MAT. PRIMA</fullName>
        <label>Materias primas</label>
    </customValue>
    <customValue>
        <fullName>MERCADERIA</fullName>
        <label>Mercaderías</label>
    </customValue>
    <customValue>
        <fullName>OTROS APRO</fullName>
        <label>Otros aprovisionamientos</label>
    </customValue>
    <customValue>
        <fullName>SERVICIOS</fullName>
        <label>Servicios</label>
    </customValue>
    <customValue>
        <fullName>TERMINADO</fullName>
        <label>Productos terminados</label>
    </customValue>
    <masterLabel>Grupo contable inventario</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ARANC CV</fullName>
        <label>Aranceles compra-venta</label>
    </customValue>
    <customValue>
        <fullName>ARANC FAB</fullName>
        <label>Aranceles fabricación</label>
    </customValue>
    <customValue>
        <fullName>GABV</fullName>
        <label>Basura, varios</label>
    </customValue>
    <customValue>
        <fullName>GAEN</fullName>
        <label>Envases</label>
    </customValue>
    <customValue>
        <fullName>GAENA</fullName>
        <label>Envases de automoción</label>
    </customValue>
    <customValue>
        <fullName>GAMEA</fullName>
        <label>Automoción</label>
    </customValue>
    <customValue>
        <fullName>GAMEC</fullName>
        <label>Mercadería compra-venta</label>
    </customValue>
    <customValue>
        <fullName>GAMEF</fullName>
        <label>Mercadería fabricación</label>
    </customValue>
    <customValue>
        <fullName>GAMEI</fullName>
        <label>Mercadería intermediación internacional</label>
    </customValue>
    <customValue>
        <fullName>GAMP</fullName>
        <label>Materia prima</label>
    </customValue>
    <customValue>
        <fullName>GAOA</fullName>
        <label>Otros Aprovisionamientos</label>
    </customValue>
    <customValue>
        <fullName>GAPO</fullName>
        <label>Porte de ventas</label>
    </customValue>
    <customValue>
        <fullName>GAPP</fullName>
        <label>Porte sobre compras</label>
    </customValue>
    <customValue>
        <fullName>VARIOS</fullName>
        <label>Otros diversos, trabajos</label>
    </customValue>
    <customValue>
        <fullName>GAENC</fullName>
        <label>Envases compra-venta</label>
    </customValue>
    <customValue>
        <fullName>TRUEN</fullName>
    </customValue>
    <customValue>
        <fullName>GAMU</fullName>
        <label>Productos de muestra</label>
    </customValue>
    <customValue>
        <fullName>IMP. PLA.</fullName>
    </customValue>
    <customValue>
        <fullName>ARANC INT</fullName>
    </customValue>
    <masterLabel>Grupo contable producto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_prod_Servicio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GR1</fullName>
    </customValue>
    <masterLabel>Grupo prod. Servicio</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_registro_IVA_prod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EXENTO</fullName>
        <label>Varios IVA Exento</label>
    </customValue>
    <customValue>
        <fullName>IVA04</fullName>
        <label>Varios con IVA 4% supereducido</label>
    </customValue>
    <customValue>
        <fullName>IVA10</fullName>
        <label>Varios con IVA 10% reducido</label>
    </customValue>
    <customValue>
        <fullName>IVA21</fullName>
        <label>Varios con IVA 21%</label>
    </customValue>
    <customValue>
        <fullName>IVABI21</fullName>
        <label>Bienes de inversión 21%</label>
    </customValue>
    <customValue>
        <fullName>IVAS21</fullName>
        <label>Varios servicios con IVA 21%</label>
    </customValue>
    <customValue>
        <fullName>IVA-TI-21</fullName>
        <label>Varios con IVA 21% importación</label>
    </customValue>
    <customValue>
        <fullName>NO SUJETO</fullName>
        <label>Varios IVA NO SUJETO</label>
    </customValue>
    <masterLabel>Grupo registro IVA prod.</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Material_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PP</fullName>
        <label>POLIPROPILENO</label>
    </customValue>
    <customValue>
        <fullName>PS</fullName>
        <label>POLIESTIRENO</label>
    </customValue>
    <customValue>
        <fullName>RPP</fullName>
        <label>PP RECICLADO</label>
    </customValue>
    <customValue>
        <fullName>RPS</fullName>
        <label>PS RECICLADO</label>
    </customValue>
    <masterLabel>Material producto</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestIntegrationUpsertTarifa.cls
@isTest
public class TestIntegrationUpsertTarifa extends IntegrationModels {
    
    @TestSetup
    static void makeData(){
        TrgController.setDoNotRunTrigger();

        Product2 productTest = new Product2(
            IsActive = true,
            DisplayUrl = 'foto',
            ERUM_External_ProductCode__c = 'no',
            Name = 'name',
            ERUM_Tipo__c = 'Inventario',
            ERUM_Bloqueado__c = false,
            QuantityUnitOfMeasure = 'unidadMedidaVenta',
            ERUM_Cod_categoria_producto__c = 'ALMACEN',
            ERUM_Cod_grupo_producto__c = 'ADZ',
            ERUM_Grupo_prod_Servicio__c = 'GR1',
            ERUM_Material_producto__c = 'PP',
            CurrencyIsoCode = 'EUR',
            ERUM_Volumen__c = 1.0,
            ERUM_Media_percha__c = 1.0,
            ERUM_Ancho_pala__c = 1.0,
            ERUM_Peso_neto__c = 1.0,
            ERUM_Peso_bruto__c = 1.0,
            ERUM_Grupo_contable_producto__c = 'ARANC CV',
            ERUM_Grupo_registro_IVA_prod__c = 'EXENTO',
            ERUM_Grupo_contable_inventario__c = 'ENVASES',
            ProductCode = 'codigoArancelario',
            ERUM_Tipo_palet__c = 'Europeo',
            ERUM_Cantidad_por_palet__c = 1.0,
            ERUM_Stock_disponible__c = 1.0,
            ERUM_Largo_embalaje__c = 1.0,
            ERUM_Ancho_embalaje__c = 1.0,
            ERUM_Alto_embalaje__c = 1.0,
            ERUM_Peso_embalaje__c = 1.0,
            ERUM_Volumen_embalaje__c = 1.0,
            ERUM_Unidad_embalaje__c = 1.0,
            ERUM_Tipo_de_material__c = 'PP',
            ERUM_Peso_neto_cantidad_embalada__c = 1.0,
            ERUM_Peso_bruto_cantidad_embalada__c = 1.0,
            ERUM_Tipo_de_materia_prima__c = 'No procede',
            ERUM_Nivel_tecnoligico__c = 'No procede',
            Family = 'tipoProducto',
            Description = 'descripcionProducto',
            ERUM_Enviada_ERP__c = false,
            Fecha_envio_ERP__c = System.today()
        );
        insert productTest;

        Product2 productTestSinTarifa = new Product2(
            IsActive = true,
            DisplayUrl = 'foto1',
            ERUM_External_ProductCode__c = 'no1',
            Name = 'name1',
            ERUM_Tipo__c = 'Inventario',
            ERUM_Bloqueado__c = false,
            QuantityUnitOfMeasure = 'unidadMedidaVenta1',
            ERUM_Cod_categoria_producto__c = 'ALMACEN',
            ERUM_Cod_grupo_producto__c = 'ADZ',
            ERUM_Grupo_prod_Servicio__c = 'GR1',
            ERUM_Material_producto__c = 'PP',
            CurrencyIsoCode = 'EUR',
            ERUM_Volumen__c = 1.0,
            ERUM_Media_percha__c = 1.0,
            ERUM_Ancho_pala__c = 1.0,
            ERUM_Peso_neto__c = 1.0,
            ERUM_Peso_bruto__c = 1.0,
            ERUM_Grupo_contable_producto__c = 'ARANC CV',
            ERUM_Grupo_registro_IVA_prod__c = 'EXENTO',
            ERUM_Grupo_contable_inventario__c = 'ENVASES',
            ProductCode = 'codigoArancelario1',
            ERUM_Tipo_palet__c = 'Europeo',
            ERUM_Cantidad_por_palet__c = 1.0,
            ERUM_Stock_disponible__c = 1.0,
            ERUM_Largo_embalaje__c = 1.0,
            ERUM_Ancho_embalaje__c = 1.0,
            ERUM_Alto_embalaje__c = 1.0,
            ERUM_Peso_embalaje__c = 1.0,
            ERUM_Volumen_embalaje__c = 1.0,
            ERUM_Unidad_embalaje__c = 1.0,
            ERUM_Tipo_de_material__c = 'PP',
            ERUM_Peso_neto_cantidad_embalada__c = 1.0,
            ERUM_Peso_bruto_cantidad_embalada__c = 1.0,
            ERUM_Tipo_de_materia_prima__c = 'No procede',
            ERUM_Nivel_tecnoligico__c = 'No procede',
            Family = 'tipoProducto1',
            Description = 'descripcionProducto1',
            ERUM_Enviada_ERP__c = false,
            Fecha_envio_ERP__c = System.today()
        );
        insert productTestSinTarifa;

        Pricebook2 tarifaTest = new Pricebook2(
            Name = 'nombre',
            Description = 'descripcion',
            IsActive = true,
            ERUM_Moneda__c = 1.0,
            ERUM_Fecha_Inicio__c = System.today(),
            ERUM_Fecha_Final__c = System.today(),
            ERUM_PB_Id_External__c = 'externalId'
        );
        insert tarifaTest;

        PricebookEntry standardEntryTest = new PricebookEntry(
            ERUM_Tipo_de_venta__c = 'Cliente',
            ERUM_Codigo_de_ventas__c = 'cvStandard',
            ERUM_Nombre_codigo_de_ventas__c = 'nombreCVS',
            C_d_Unidad_de_medida__c = 'CAJA',
            UnitPrice = 1.0,
            ERUM_Fecha_Inicial__c = System.today(),
            ERUM_Fecha_Final__c = System.today(),
            ERUM_Incluir_coste_contenedor__c = false,
            CurrencyIsoCode = 'EUR',
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = productTest.Id,
            Id_LineaTarifa__c = null
        );
        insert standardEntryTest;

        PricebookEntry entryTest = new PricebookEntry(
            ERUM_Tipo_de_venta__c = 'Cliente',
            ERUM_Codigo_de_ventas__c = 'codVentas',
            ERUM_Nombre_codigo_de_ventas__c = 'nombreCV',
            C_d_Unidad_de_medida__c = 'CAJA',
            UnitPrice = 2.0,
            ERUM_Fecha_Inicial__c = System.today(),
            ERUM_Fecha_Final__c = System.today(),
            ERUM_Incluir_coste_contenedor__c = false,
            CurrencyIsoCode = 'EUR',
            Pricebook2Id = tarifaTest.Id,
            Product2Id = productTest.Id,
            Id_LineaTarifa__c = 0
        );
        insert entryTest;

        Pricebook2 tarifaTestSinLineas = new Pricebook2(
            Name = 'nombreSinLineas',
            Description = 'descripcioSinLineas',
            IsActive = true,
            ERUM_Moneda__c = 100.0,
            ERUM_Fecha_Inicio__c = System.today(),
            ERUM_Fecha_Final__c = System.today(),
            ERUM_PB_Id_External__c = 'externalIdSinLineas'
        );
        insert tarifaTestSinLineas;
    }

    /**
     * INSERCIÓN DE UNA TARIFA Y SUS LÍNEAS CON ÉXITO
     */

    @isTest(SeeAllData=false)
    public static void upsertTarifa_Test1() {
        
        RequestBodyTarifa tarifaTest = new RequestBodyTarifa();
        tarifaTest.activa = true;
        tarifaTest.nombre = 'nombre1';
        tarifaTest.descripcion = 'descripcion1';
        tarifaTest.moneda = 1.1;
        tarifaTest.fechaInicio = System.today();
        tarifaTest.fechaFin = System.today();
        tarifaTest.externalId = 'externalId1';

        RequestBodyLineaTarifa lineaTarifaTest = new RequestBodyLineaTarifa();
        lineaTarifaTest.tipoVenta = 'Cliente';
        lineaTarifaTest.codVentas = 'codVentas1';
        lineaTarifaTest.nombreCodVentas = 'nombreCV1';
        lineaTarifaTest.codUdMedida = 'CAJA';
        lineaTarifaTest.precioVenta = 1.1;
        lineaTarifaTest.fechaInicial = System.today();
        lineaTarifaTest.fechaFinal = System.today();
        lineaTarifaTest.incluirCosteContenedor = false;
        lineaTarifaTest.divisa = 'EUR';
        lineaTarifaTest.productNo = 'no';
        lineaTarifaTest.idLineaTarifa = 1;
        
        List<RequestBodyLineaTarifa> lineas = new List<RequestBodyLineaTarifa>();
        lineas.add(lineaTarifaTest);
        tarifaTest.entradas = lineas;

        IntegrationUpsertTarifa.upsertTarifa(tarifaTest);
    }

    /**
     * INSERCIÓN DE UNA TARIFA SIN LÍNEAS CON ÉXITO
     */

    @isTest(SeeAllData=false)
    public static void upsertTarifa_Test2() {
        
        RequestBodyTarifa tarifaTest = new RequestBodyTarifa();
        tarifaTest.activa = true;
        tarifaTest.nombre = 'nombre2';
        tarifaTest.descripcion = 'descripcion2';
        tarifaTest.moneda = 2.2;
        tarifaTest.fechaInicio = System.today();
        tarifaTest.fechaFin = System.today();
        tarifaTest.externalId = 'externalId2';

        IntegrationUpsertTarifa.upsertTarifa(tarifaTest);
    }

    /**
     * INSERCIÓN DE UNA NUEVA LÍNEA EN UNA TARIFA EXISTENTE CON LÍNEAS CON ÉXITO
     */

    @isTest(SeeAllData=false)
    public static void upsertTarifa_Test3() {
        
        RequestBodyTarifa tarifaTest = new RequestBodyTarifa();
        tarifaTest.activa = true;
        tarifaTest.nombre = 'nombre';
        tarifaTest.descripcion = 'descripcion';
        tarifaTest.moneda = 3.3;
        tarifaTest.fechaInicio = System.today();
        tarifaTest.fechaFin = System.today();
        tarifaTest.externalId = 'externalId';

        RequestBodyLineaTarifa lineaTarifaTest = new RequestBodyLineaTarifa();
        lineaTarifaTest.tipoVenta = 'Cliente';
        lineaTarifaTest.codVentas = 'codVentas3';
        lineaTarifaTest.nombreCodVentas = 'nombreCV3';
        lineaTarifaTest.codUdMedida = 'CAJA';
        lineaTarifaTest.precioVenta = 3.3;
        lineaTarifaTest.fechaInicial = System.today();
        lineaTarifaTest.fechaFinal = System.today();
        lineaTarifaTest.incluirCosteContenedor = false;
        lineaTarifaTest.divisa = 'EUR';
        lineaTarifaTest.productNo = 'no1';
        lineaTarifaTest.idLineaTarifa = 3;
        
        List<RequestBodyLineaTarifa> lineas = new List<RequestBodyLineaTarifa>();
        lineas.add(lineaTarifaTest);
        tarifaTest.entradas = lineas;

        IntegrationUpsertTarifa.upsertTarifa(tarifaTest);
    }

    /**
     * INSERCIÓN DE UNA NUEVA LÍNEA EN UNA TARIFA EXISTENTE SIN LÍNEAS CON ÉXITO
     */

    @isTest(SeeAllData=false)
    public static void upsertTarifa_Test4() {
        
        RequestBodyTarifa tarifaTest = new RequestBodyTarifa();
        tarifaTest.activa = true;
        tarifaTest.nombre = 'nombreSinLineas';
        tarifaTest.descripcion = 'descripcionSinLineas';
        tarifaTest.moneda = 4.4;
        tarifaTest.fechaInicio = System.today();
        tarifaTest.fechaFin = System.today();
        tarifaTest.externalId = 'externalIdSinLineas';

        RequestBodyLineaTarifa lineaTarifaTest = new RequestBodyLineaTarifa();
        lineaTarifaTest.tipoVenta = 'Cliente';
        lineaTarifaTest.codVentas = 'codVentas4';
        lineaTarifaTest.nombreCodVentas = 'nombreCV4';
        lineaTarifaTest.codUdMedida = 'CAJA';
        lineaTarifaTest.precioVenta = 4.4;
        lineaTarifaTest.fechaInicial = System.today();
        lineaTarifaTest.fechaFinal = System.today();
        lineaTarifaTest.incluirCosteContenedor = false;
        lineaTarifaTest.divisa = 'EUR';
        lineaTarifaTest.productNo = 'no1';
        lineaTarifaTest.idLineaTarifa = 4;
        
        List<RequestBodyLineaTarifa> lineas = new List<RequestBodyLineaTarifa>();
        lineas.add(lineaTarifaTest);
        tarifaTest.entradas = lineas;

        IntegrationUpsertTarifa.upsertTarifa(tarifaTest);
    }

    /**
     * ERROR AL INSERTAR/EDITAR TARIFA SIN LÍNEAS
     */
    @isTest(SeeAllData=false)
    public static void upsertTarifa_Test5() {
        
        RequestBodyTarifa tarifaTest = new RequestBodyTarifa();
        tarifaTest.activa = true;
        tarifaTest.nombre = 'nombre5';
        tarifaTest.descripcion = 'descripcion5';
        tarifaTest.moneda = 12345678910.12;
        tarifaTest.fechaInicio = System.today();
        tarifaTest.fechaFin = System.today();
        tarifaTest.externalId = 'externalId5';

        IntegrationUpsertTarifa.upsertTarifa(tarifaTest);
    }

    /**
     * ERROR AL ENCONTRAR PRODUCTO DE LÍNEA DE TARIFA
     */
    @isTest(SeeAllData=false)
    public static void upsertTarifa_Test6() {
        
        RequestBodyTarifa tarifaTest = new RequestBodyTarifa();
        tarifaTest.activa = true;
        tarifaTest.nombre = 'nombre6';
        tarifaTest.descripcion = 'descripcion6';
        tarifaTest.moneda = 6.6;
        tarifaTest.fechaInicio = System.today();
        tarifaTest.fechaFin = System.today();
        tarifaTest.externalId = 'externalId6';

        RequestBodyLineaTarifa lineaTarifaTest = new RequestBodyLineaTarifa();
        lineaTarifaTest.tipoVenta = 'Cliente';
        lineaTarifaTest.codVentas = 'codVentas6';
        lineaTarifaTest.nombreCodVentas = 'nombreCV6';
        lineaTarifaTest.codUdMedida = 'CAJA';
        lineaTarifaTest.precioVenta = 6.6;
        lineaTarifaTest.fechaInicial = System.today();
        lineaTarifaTest.fechaFinal = System.today();
        lineaTarifaTest.incluirCosteContenedor = false;
        lineaTarifaTest.divisa = 'EUR';
        lineaTarifaTest.productNo = 'no_6_inexistente';
        lineaTarifaTest.idLineaTarifa = 6;
        
        List<RequestBodyLineaTarifa> lineas = new List<RequestBodyLineaTarifa>();
        lineas.add(lineaTarifaTest);
        tarifaTest.entradas = lineas;

        IntegrationUpsertTarifa.upsertTarifa(tarifaTest);
    }

    
    /**
     * ERROR AL INSERTAR LÍNEAS
     */

    @isTest(SeeAllData=false)
    public static void upsertTarifa_Test7() {
         
        RequestBodyTarifa tarifaTest = new RequestBodyTarifa();
        tarifaTest.activa = true;
        tarifaTest.nombre = 'nombre';
        tarifaTest.descripcion = 'descripcion';
        tarifaTest.moneda = 7.7;
        tarifaTest.fechaInicio = System.today();
        tarifaTest.fechaFin = System.today();
        tarifaTest.externalId = 'externalId';
 
        RequestBodyLineaTarifa lineaTarifaTest = new RequestBodyLineaTarifa();
        lineaTarifaTest.tipoVenta = 'Cliente';
        lineaTarifaTest.codVentas = 'codVentas7';
        lineaTarifaTest.nombreCodVentas = 'nombreCV7';
        lineaTarifaTest.codUdMedida = 'FGASGASGA';
        lineaTarifaTest.precioVenta = 7.7;
        lineaTarifaTest.fechaInicial = System.today();
        lineaTarifaTest.fechaFinal = System.today();
        lineaTarifaTest.incluirCosteContenedor = false;
        lineaTarifaTest.divisa = 'EUR';
        lineaTarifaTest.productNo = 'no1';
        lineaTarifaTest.idLineaTarifa = 7;
        
        List<RequestBodyLineaTarifa> lineas = new List<RequestBodyLineaTarifa>();
        lineas.add(lineaTarifaTest);
        tarifaTest.entradas = lineas;
 
        IntegrationUpsertTarifa.upsertTarifa(tarifaTest);
    }

    /**
    * ERROR AL EDITAR LÍNEAS
    */

    @isTest(SeeAllData=false)
    public static void upsertTarifa_Test8() {
         
        RequestBodyTarifa tarifaTest = new RequestBodyTarifa();
        tarifaTest.activa = true;
        tarifaTest.nombre = 'nombre';
        tarifaTest.descripcion = 'descripcion';
        tarifaTest.moneda = 8.8;
        tarifaTest.fechaInicio = System.today();
        tarifaTest.fechaFin = System.today();
        tarifaTest.externalId = 'externalId';
 
        RequestBodyLineaTarifa lineaTarifaTest = new RequestBodyLineaTarifa();
        lineaTarifaTest.tipoVenta = 'Cliente';
        lineaTarifaTest.codVentas = 'codVentas8';
        lineaTarifaTest.nombreCodVentas = 'nombreCV8';
        lineaTarifaTest.codUdMedida = 'WASDDGDSFH';
        lineaTarifaTest.precioVenta = 8.8;
        lineaTarifaTest.fechaInicial = System.today();
        lineaTarifaTest.fechaFinal = System.today();
        lineaTarifaTest.incluirCosteContenedor = false;
        lineaTarifaTest.divisa = 'EUR';
        lineaTarifaTest.productNo = 'no';
        lineaTarifaTest.idLineaTarifa = 8;
        
        List<RequestBodyLineaTarifa> lineas = new List<RequestBodyLineaTarifa>();
        lineas.add(lineaTarifaTest);
        tarifaTest.entradas = lineas;
 
        IntegrationUpsertTarifa.upsertTarifa(tarifaTest);
    }

    /**
     * ERROR INTERNO DEL SERVIDOR
     */

     @isTest(SeeAllData=false)
     public static void upsertTarifa_Test9() {
        IntegrationUpsertTarifa.upsertTarifa(null);
    }
}