force-app/main/default/objects/Product2/fields/ERUM_Alto_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Alto_embalaje__c</fullName>
    <label>Alto embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Ancho_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Ancho_embalaje__c</fullName>
    <label>Ancho embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Ancho_pala__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Ancho_pala__c</fullName>
    <label>Ancho pala</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Bloqueado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Bloqueado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bloqueado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cantidad_por_palet__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cantidad_por_palet__c</fullName>
    <label>Cantidad por palet</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cod_categoria_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cod_categoria_producto__c</fullName>
    <label>Cód.categoría producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cod_categoria_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cod_grupo_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cod_grupo_producto__c</fullName>
    <label>Cód. grupo producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cod_grupo_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Enviada_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Enviada_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviada ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_External_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ERUM_External_ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>Código Producto BC</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_contable_inventario__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_contable_inventario__c</fullName>
    <label>Grupo contable inventario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_inventario</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_contable_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_contable_producto__c</fullName>
    <label>Grupo contable producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_prod_Servicio__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_prod_Servicio__c</fullName>
    <label>Grupo prod. Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_prod_Servicio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_registro_IVA_prod__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_registro_IVA_prod__c</fullName>
    <label>Grupo registro IVA prod.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_registro_IVA_prod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Largo_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Largo_embalaje__c</fullName>
    <label>Largo embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Material_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Material_producto__c</fullName>
    <label>Material producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Media_percha__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Media_percha__c</fullName>
    <label>Media percha</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Nivel_tecnoligico__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Nivel_tecnoligico__c</fullName>
    <label>Nivel tecnológico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procede</fullName>
            </value>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_bruto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_bruto__c</fullName>
    <label>Peso bruto</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_bruto_cantidad_embalada__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_bruto_cantidad_embalada__c</fullName>
    <label>Peso bruto cantidad embalada</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_embalaje__c</fullName>
    <label>Peso embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_neto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_neto__c</fullName>
    <label>Peso neto</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_neto_cantidad_embalada__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_neto_cantidad_embalada__c</fullName>
    <label>Peso neto cantidad embalada</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Stock_disponible__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Stock_disponible__c</fullName>
    <inlineHelpText>Recuerde actualizar la página al consultar el Stock, tras 30 segundos, pulsando: &quot;ctrl&quot; + &quot;F5&quot;.</inlineHelpText>
    <label>Stock disponible</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventario</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_de_materia_prima__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_de_materia_prima__c</fullName>
    <label>Tipo de materia prima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procede</fullName>
            </value>
            <value>
                <fullName>Virgen</fullName>
            </value>
            <value>
                <fullName>Reciclado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_de_material__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_de_material__c</fullName>
    <label>Tipo de material</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_palet__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_palet__c</fullName>
    <label>Tipo palet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Europeo</fullName>
            </value>
            <value>
                <fullName>Americano</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Unidad_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Unidad_embalaje__c</fullName>
    <label>Unidad embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Volumen__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Volumen__c</fullName>
    <label>Volumen</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Volumen_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Volumen_embalaje__c</fullName>
    <label>Volumen embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_envio_ERP__c.field-meta.xml
<CustomField>
    <fullName>Fecha_envio_ERP__c</fullName>
    <label>Fecha envío ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Cod_categoria_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALMACEN</fullName>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
        <label>COMPLEMENTOS MADERA</label>
    </customValue>
    <customValue>
        <fullName>CP</fullName>
        <label>COMPLEMENTOS PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>MLD02549</fullName>
        <label>CRF06 30</label>
    </customValue>
    <customValue>
        <fullName>MPM</fullName>
        <label>MATERIA PRIMA MADERA</label>
    </customValue>
    <customValue>
        <fullName>MPP</fullName>
        <label>MATERIA PRIMA PLÁSTICOMATERIA PRIMA PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>PIM</fullName>
        <label>PRODUCTO INTERMEDIO MADERA</label>
    </customValue>
    <customValue>
        <fullName>PIP</fullName>
        <label>PRODUCTO INTERMEDIO PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>PTM</fullName>
        <label>PRODUCTO TERMINADO MADERA</label>
    </customValue>
    <customValue>
        <fullName>PTP</fullName>
        <label>PRODUCTO TERMINADO PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>SIN</fullName>
        <label>SIN CLASIFICACION</label>
    </customValue>
    <masterLabel>Cód. categoría producto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_inventario.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ENVASES</fullName>
        <label>Envases y embalajes</label>
    </customValue>
    <customValue>
        <fullName>MAT. PRIMA</fullName>
        <label>Materias primas</label>
    </customValue>
    <customValue>
        <fullName>MERCADERIA</fullName>
        <label>Mercaderías</label>
    </customValue>
    <customValue>
        <fullName>OTROS APRO</fullName>
        <label>Otros aprovisionamientos</label>
    </customValue>
    <customValue>
        <fullName>SERVICIOS</fullName>
        <label>Servicios</label>
    </customValue>
    <customValue>
        <fullName>TERMINADO</fullName>
        <label>Productos terminados</label>
    </customValue>
    <masterLabel>Grupo contable inventario</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ARANC CV</fullName>
        <label>Aranceles compra-venta</label>
    </customValue>
    <customValue>
        <fullName>ARANC FAB</fullName>
        <label>Aranceles fabricación</label>
    </customValue>
    <customValue>
        <fullName>GABV</fullName>
        <label>Basura, varios</label>
    </customValue>
    <customValue>
        <fullName>GAEN</fullName>
        <label>Envases</label>
    </customValue>
    <customValue>
        <fullName>GAENA</fullName>
        <label>Envases de automoción</label>
    </customValue>
    <customValue>
        <fullName>GAMEA</fullName>
        <label>Automoción</label>
    </customValue>
    <customValue>
        <fullName>GAMEC</fullName>
        <label>Mercadería compra-venta</label>
    </customValue>
    <customValue>
        <fullName>GAMEF</fullName>
        <label>Mercadería fabricación</label>
    </customValue>
    <customValue>
        <fullName>GAMEI</fullName>
        <label>Mercadería intermediación internacional</label>
    </customValue>
    <customValue>
        <fullName>GAMP</fullName>
        <label>Materia prima</label>
    </customValue>
    <customValue>
        <fullName>GAOA</fullName>
        <label>Otros Aprovisionamientos</label>
    </customValue>
    <customValue>
        <fullName>GAPO</fullName>
        <label>Porte de ventas</label>
    </customValue>
    <customValue>
        <fullName>GAPP</fullName>
        <label>Porte sobre compras</label>
    </customValue>
    <customValue>
        <fullName>VARIOS</fullName>
        <label>Otros diversos, trabajos</label>
    </customValue>
    <customValue>
        <fullName>GAENC</fullName>
        <label>Envases compra-venta</label>
    </customValue>
    <customValue>
        <fullName>TRUEN</fullName>
    </customValue>
    <customValue>
        <fullName>GAMU</fullName>
        <label>Productos de muestra</label>
    </customValue>
    <customValue>
        <fullName>IMP. PLA.</fullName>
    </customValue>
    <customValue>
        <fullName>ARANC INT</fullName>
    </customValue>
    <masterLabel>Grupo contable producto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_prod_Servicio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GR1</fullName>
    </customValue>
    <masterLabel>Grupo prod. Servicio</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_registro_IVA_prod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EXENTO</fullName>
        <label>Varios IVA Exento</label>
    </customValue>
    <customValue>
        <fullName>IVA04</fullName>
        <label>Varios con IVA 4% supereducido</label>
    </customValue>
    <customValue>
        <fullName>IVA10</fullName>
        <label>Varios con IVA 10% reducido</label>
    </customValue>
    <customValue>
        <fullName>IVA21</fullName>
        <label>Varios con IVA 21%</label>
    </customValue>
    <customValue>
        <fullName>IVABI21</fullName>
        <label>Bienes de inversión 21%</label>
    </customValue>
    <customValue>
        <fullName>IVAS21</fullName>
        <label>Varios servicios con IVA 21%</label>
    </customValue>
    <customValue>
        <fullName>IVA-TI-21</fullName>
        <label>Varios con IVA 21% importación</label>
    </customValue>
    <customValue>
        <fullName>NO SUJETO</fullName>
        <label>Varios IVA NO SUJETO</label>
    </customValue>
    <masterLabel>Grupo registro IVA prod.</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Material_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PP</fullName>
        <label>POLIPROPILENO</label>
    </customValue>
    <customValue>
        <fullName>PS</fullName>
        <label>POLIESTIRENO</label>
    </customValue>
    <customValue>
        <fullName>RPP</fullName>
        <label>PP RECICLADO</label>
    </customValue>
    <customValue>
        <fullName>RPS</fullName>
        <label>PS RECICLADO</label>
    </customValue>
    <masterLabel>Material producto</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestProductStock.cls
@isTest
public class TestProductStock {
    
    public class StockMock implements WebServiceMock {
        public void doInvoke(
            Object stub,
            Object request,
            Map<String, Object> response,
            String endpoint,
            String soapAction,
            String requestName,
            String responseNS,
            String responseName,
            String responseType
        ) {

            AitanaProductStock.wsSF_Stocks producto = new AitanaProductStock.wsSF_Stocks();
            producto.Key = 'test';
            producto.No = 'no';
            producto.Inventory = 100;
            producto.StockDisponible = 50;
            if (requestName == 'Read') {
                AitanaProductStock.Read_Result_element readResult = new AitanaProductStock.Read_Result_element();
                readResult.wsSF_Stocks = producto;
                response.put('response_x', readResult);
            }
        }
    }

    @TestSetup
    static void makeData(){
        TrgController.setDoNotRunTrigger();
        Product2 productTest = new Product2(
            IsActive = true,
            DisplayUrl = 'foto',
            ERUM_External_ProductCode__c = 'no',
            Name = 'name',
            ERUM_Tipo__c = 'Inventario',
            ERUM_Bloqueado__c = false,
            QuantityUnitOfMeasure = 'unidadMedidaVenta',
            ERUM_Cod_categoria_producto__c = 'ALMACEN',
            ERUM_Cod_grupo_producto__c = 'ADZ',
            ERUM_Grupo_prod_Servicio__c = 'GR1',
            ERUM_Material_producto__c = 'PP',
            CurrencyIsoCode = 'EUR',
            ERUM_Volumen__c = 1.0,
            ERUM_Media_percha__c = 1.0,
            ERUM_Ancho_pala__c = 1.0,
            ERUM_Peso_neto__c = 1.0,
            ERUM_Peso_bruto__c = 1.0,
            ERUM_Grupo_contable_producto__c = 'ARANC CV',
            ERUM_Grupo_registro_IVA_prod__c = 'EXENTO',
            ERUM_Grupo_contable_inventario__c = 'ENVASES',
            ProductCode = 'codigoArancelario',
            ERUM_Tipo_palet__c = 'Europeo',
            ERUM_Cantidad_por_palet__c = 1.0,
            ERUM_Stock_disponible__c = 1.0,
            ERUM_Largo_embalaje__c = 1.0,
            ERUM_Ancho_embalaje__c = 1.0,
            ERUM_Alto_embalaje__c = 1.0,
            ERUM_Peso_embalaje__c = 1.0,
            ERUM_Volumen_embalaje__c = 1.0,
            ERUM_Unidad_embalaje__c = 1.0,
            ERUM_Tipo_de_material__c = 'PP',
            ERUM_Peso_neto_cantidad_embalada__c = 1.0,
            ERUM_Peso_bruto_cantidad_embalada__c = 1.0,
            ERUM_Tipo_de_materia_prima__c = 'No procede',
            ERUM_Nivel_tecnoligico__c = 'No procede',
            Family = 'tipoProducto',
            Description = 'descripcionProducto',
            ERUM_Enviada_ERP__c = false,
            Fecha_envio_ERP__c = System.today()
        );
        insert productTest;
    }

    @isTest
    public static void testProductStock_1() {
        Product2 test1 = [SELECT Id, ERUM_External_ProductCode__c FROM Product2 WHERE ERUM_External_ProductCode__c =: 'no' LIMIT 1];
        Pagereference pRef = Page.ButtonWSProductStockPage;
        Test.setMock(WebServiceMock.class, new StockMock());
        Test.setCurrentPage(pRef);
        Test.startTest();
        ApexPages.StandardController sCtrl = new ApexPages.StandardController(test1);
        ButtonWSProductStockController ctrl = new ButtonWSProductStockController(sCtrl);
        ctrl.updateStock();
        Test.stopTest();
    }
}