force-app/main/default/objects/Product2/fields/ERUM_Alto_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Alto_embalaje__c</fullName>
    <label>Alto embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Ancho_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Ancho_embalaje__c</fullName>
    <label>Ancho embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Ancho_pala__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Ancho_pala__c</fullName>
    <label>Ancho pala</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Bloqueado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Bloqueado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bloqueado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cantidad_por_palet__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cantidad_por_palet__c</fullName>
    <label>Cantidad por palet</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cod_categoria_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cod_categoria_producto__c</fullName>
    <label>Cód.categoría producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cod_categoria_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cod_grupo_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cod_grupo_producto__c</fullName>
    <label>Cód. grupo producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cod_grupo_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Enviada_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Enviada_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviada ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_External_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ERUM_External_ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>Código Producto BC</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_contable_inventario__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_contable_inventario__c</fullName>
    <label>Grupo contable inventario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_inventario</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_contable_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_contable_producto__c</fullName>
    <label>Grupo contable producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_prod_Servicio__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_prod_Servicio__c</fullName>
    <label>Grupo prod. Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_prod_Servicio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_registro_IVA_prod__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_registro_IVA_prod__c</fullName>
    <label>Grupo registro IVA prod.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_registro_IVA_prod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Largo_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Largo_embalaje__c</fullName>
    <label>Largo embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Material_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Material_producto__c</fullName>
    <label>Material producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Media_percha__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Media_percha__c</fullName>
    <label>Media percha</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Nivel_tecnoligico__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Nivel_tecnoligico__c</fullName>
    <label>Nivel tecnológico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procede</fullName>
            </value>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_bruto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_bruto__c</fullName>
    <label>Peso bruto</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_bruto_cantidad_embalada__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_bruto_cantidad_embalada__c</fullName>
    <label>Peso bruto cantidad embalada</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_embalaje__c</fullName>
    <label>Peso embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_neto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_neto__c</fullName>
    <label>Peso neto</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_neto_cantidad_embalada__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_neto_cantidad_embalada__c</fullName>
    <label>Peso neto cantidad embalada</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Stock_disponible__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Stock_disponible__c</fullName>
    <inlineHelpText>Recuerde actualizar la página al consultar el Stock, tras 30 segundos, pulsando: &quot;ctrl&quot; + &quot;F5&quot;.</inlineHelpText>
    <label>Stock disponible</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventario</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_de_materia_prima__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_de_materia_prima__c</fullName>
    <label>Tipo de materia prima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procede</fullName>
            </value>
            <value>
                <fullName>Virgen</fullName>
            </value>
            <value>
                <fullName>Reciclado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_de_material__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_de_material__c</fullName>
    <label>Tipo de material</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_palet__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_palet__c</fullName>
    <label>Tipo palet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Europeo</fullName>
            </value>
            <value>
                <fullName>Americano</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Unidad_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Unidad_embalaje__c</fullName>
    <label>Unidad embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Volumen__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Volumen__c</fullName>
    <label>Volumen</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Volumen_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Volumen_embalaje__c</fullName>
    <label>Volumen embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_envio_ERP__c.field-meta.xml
<CustomField>
    <fullName>Fecha_envio_ERP__c</fullName>
    <label>Fecha envío ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Cod_categoria_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALMACEN</fullName>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
        <label>COMPLEMENTOS MADERA</label>
    </customValue>
    <customValue>
        <fullName>CP</fullName>
        <label>COMPLEMENTOS PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>MLD02549</fullName>
        <label>CRF06 30</label>
    </customValue>
    <customValue>
        <fullName>MPM</fullName>
        <label>MATERIA PRIMA MADERA</label>
    </customValue>
    <customValue>
        <fullName>MPP</fullName>
        <label>MATERIA PRIMA PLÁSTICOMATERIA PRIMA PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>PIM</fullName>
        <label>PRODUCTO INTERMEDIO MADERA</label>
    </customValue>
    <customValue>
        <fullName>PIP</fullName>
        <label>PRODUCTO INTERMEDIO PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>PTM</fullName>
        <label>PRODUCTO TERMINADO MADERA</label>
    </customValue>
    <customValue>
        <fullName>PTP</fullName>
        <label>PRODUCTO TERMINADO PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>SIN</fullName>
        <label>SIN CLASIFICACION</label>
    </customValue>
    <masterLabel>Cód. categoría producto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_inventario.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ENVASES</fullName>
        <label>Envases y embalajes</label>
    </customValue>
    <customValue>
        <fullName>MAT. PRIMA</fullName>
        <label>Materias primas</label>
    </customValue>
    <customValue>
        <fullName>MERCADERIA</fullName>
        <label>Mercaderías</label>
    </customValue>
    <customValue>
        <fullName>OTROS APRO</fullName>
        <label>Otros aprovisionamientos</label>
    </customValue>
    <customValue>
        <fullName>SERVICIOS</fullName>
        <label>Servicios</label>
    </customValue>
    <customValue>
        <fullName>TERMINADO</fullName>
        <label>Productos terminados</label>
    </customValue>
    <masterLabel>Grupo contable inventario</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ARANC CV</fullName>
        <label>Aranceles compra-venta</label>
    </customValue>
    <customValue>
        <fullName>ARANC FAB</fullName>
        <label>Aranceles fabricación</label>
    </customValue>
    <customValue>
        <fullName>GABV</fullName>
        <label>Basura, varios</label>
    </customValue>
    <customValue>
        <fullName>GAEN</fullName>
        <label>Envases</label>
    </customValue>
    <customValue>
        <fullName>GAENA</fullName>
        <label>Envases de automoción</label>
    </customValue>
    <customValue>
        <fullName>GAMEA</fullName>
        <label>Automoción</label>
    </customValue>
    <customValue>
        <fullName>GAMEC</fullName>
        <label>Mercadería compra-venta</label>
    </customValue>
    <customValue>
        <fullName>GAMEF</fullName>
        <label>Mercadería fabricación</label>
    </customValue>
    <customValue>
        <fullName>GAMEI</fullName>
        <label>Mercadería intermediación internacional</label>
    </customValue>
    <customValue>
        <fullName>GAMP</fullName>
        <label>Materia prima</label>
    </customValue>
    <customValue>
        <fullName>GAOA</fullName>
        <label>Otros Aprovisionamientos</label>
    </customValue>
    <customValue>
        <fullName>GAPO</fullName>
        <label>Porte de ventas</label>
    </customValue>
    <customValue>
        <fullName>GAPP</fullName>
        <label>Porte sobre compras</label>
    </customValue>
    <customValue>
        <fullName>VARIOS</fullName>
        <label>Otros diversos, trabajos</label>
    </customValue>
    <customValue>
        <fullName>GAENC</fullName>
        <label>Envases compra-venta</label>
    </customValue>
    <customValue>
        <fullName>TRUEN</fullName>
    </customValue>
    <customValue>
        <fullName>GAMU</fullName>
        <label>Productos de muestra</label>
    </customValue>
    <customValue>
        <fullName>IMP. PLA.</fullName>
    </customValue>
    <customValue>
        <fullName>ARANC INT</fullName>
    </customValue>
    <masterLabel>Grupo contable producto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_prod_Servicio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GR1</fullName>
    </customValue>
    <masterLabel>Grupo prod. Servicio</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_registro_IVA_prod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EXENTO</fullName>
        <label>Varios IVA Exento</label>
    </customValue>
    <customValue>
        <fullName>IVA04</fullName>
        <label>Varios con IVA 4% supereducido</label>
    </customValue>
    <customValue>
        <fullName>IVA10</fullName>
        <label>Varios con IVA 10% reducido</label>
    </customValue>
    <customValue>
        <fullName>IVA21</fullName>
        <label>Varios con IVA 21%</label>
    </customValue>
    <customValue>
        <fullName>IVABI21</fullName>
        <label>Bienes de inversión 21%</label>
    </customValue>
    <customValue>
        <fullName>IVAS21</fullName>
        <label>Varios servicios con IVA 21%</label>
    </customValue>
    <customValue>
        <fullName>IVA-TI-21</fullName>
        <label>Varios con IVA 21% importación</label>
    </customValue>
    <customValue>
        <fullName>NO SUJETO</fullName>
        <label>Varios IVA NO SUJETO</label>
    </customValue>
    <masterLabel>Grupo registro IVA prod.</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Material_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PP</fullName>
        <label>POLIPROPILENO</label>
    </customValue>
    <customValue>
        <fullName>PS</fullName>
        <label>POLIESTIRENO</label>
    </customValue>
    <customValue>
        <fullName>RPP</fullName>
        <label>PP RECICLADO</label>
    </customValue>
    <customValue>
        <fullName>RPS</fullName>
        <label>PS RECICLADO</label>
    </customValue>
    <masterLabel>Material producto</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IntegrationUpsertProduct.cls
global class IntegrationUpsertProduct extends IntegrationModels {
    
    webservice static Response upsertProduct(RequestBodyProduct productObject) {
        Savepoint sp = Database.setSavepoint();
        try {

            Product2 product = new Product2(
                IsActive = true,
                DisplayUrl = productObject.foto,
                ERUM_External_ProductCode__c = productObject.no,
                Name = productObject.descripcionProducto,
                ERUM_Tipo__c = productObject.tipo,
                ERUM_Bloqueado__c = productObject.bloqueado,
                QuantityUnitOfMeasure = productObject.unidadMedidaVenta,
                ERUM_Cod_categoria_producto__c = productObject.codigoCategoria,
                ERUM_Cod_grupo_producto__c = productObject.codigoGrupoProducto,
                ERUM_Grupo_prod_Servicio__c = productObject.grupoProductoServicio,
                ERUM_Material_producto__c = productObject.material,
                CurrencyIsoCode = productObject.divisa,
                ERUM_Volumen__c = productObject.volumen,
                ERUM_Media_percha__c = productObject.medidaPercha,
                ERUM_Ancho_pala__c = productObject.anchoPala,
                ERUM_Peso_neto__c = productObject.pesoNeto,
                ERUM_Peso_bruto__c = productObject.pesoBruto,
                ERUM_Grupo_contable_producto__c = productObject.grupoContable,
                ERUM_Grupo_registro_IVA_prod__c = productObject.grupoRegistroIVA,
                ERUM_Grupo_contable_inventario__c = productObject.grupoContableInventario,
                ProductCode = productObject.codigoArancelario,
                ERUM_Tipo_palet__c = productObject.tipoPalet,
                ERUM_Cantidad_por_palet__c = productObject.cantidadPorPalet,
                ERUM_Stock_disponible__c = productObject.stockDisponible,
                ERUM_Largo_embalaje__c = productObject.largoEmbalaje,
                ERUM_Ancho_embalaje__c = productObject.anchoEmbalaje,
                ERUM_Alto_embalaje__c = productObject.altoEmbalaje,
                ERUM_Peso_embalaje__c = productObject.pesoEmbalaje,
                ERUM_Volumen_embalaje__c = productObject.volumenEmbalaje,
                ERUM_Unidad_embalaje__c = productObject.unidadEmbalaje,
                ERUM_Tipo_de_material__c = productObject.tipoMaterial,
                ERUM_Peso_neto_cantidad_embalada__c = productObject.pesoNetoCantidadEmbalada,
                ERUM_Peso_bruto_cantidad_embalada__c = productObject.pesoBrutoCantidadEmbalada,
                ERUM_Tipo_de_materia_prima__c = productObject.tipoMateriaPrima,
                ERUM_Nivel_tecnoligico__c = productObject.nivelTecnologico,
                Family = productObject.tipoProducto,
                Description = productObject.descripcionProducto,
                ERUM_Enviada_ERP__c = productObject.enviadaERP,
                Fecha_envio_ERP__c = productObject.fechaEnvioERP
            );

            try {
                Database.upsert(product, Product2.ERUM_External_ProductCode__c, true);
            } catch (DmlException dmlEx) {
                Database.rollback(sp);
                System.debug(dmlEx);
                GestionErrores.insertGestionErrores(dmlEx.getMessage(), 'Navision', 500, null, productObject.no, 'Productos');
                ErrorResponse r = new ErrorResponse();
                r.message = dmlEx.getMessage();
                r.errorType = '500 - Error al insertar/editar el producto. Detalles de la excepción: ' + dmlEx.getMessage();
                return r;
            }

            SuccessResponse r = new SuccessResponse();
            r.message = 'Producto creado/editado con éxito: ' + product.Id;
            r.Code = 'Success';
            return r;
            
        } catch (Exception e) {
            Database.rollback(sp);
            System.debug(e);
            GestionErrores.insertGestionErrores(e.getMessage(), 'Navision', 500, null, productObject != null ? productObject.no : null, 'Productos');
            ErrorResponse r = new ErrorResponse();
            r.message = e.getMessage();
            r.errorType = '500 - Error interno del servidor. Detalles de la excepción: ' + e.getMessage();
            return r;
        }
    }
}