force-app/main/default/objects/Account/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asegurado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dias_Asegurado_CYC__c.field-meta.xml
<CustomField>
    <fullName>Dias_Asegurado_CYC__c</fullName>
    <label>Días asegurado CYC</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Activo_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_CIF_Europeo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_CIF_Europeo__c</fullName>
    <label>CIF Europeo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Codigo_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Codigo_cliente_ERP__c</fullName>
    <externalId>true</externalId>
    <label>Código cliente ERP</label>
    <length>225</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Email__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Estado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Estado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Fecha_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Activo_ERP__c</fullName>
    <label>Fecha Activo ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Forma_de_pago__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Forma_de_pago__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Forma_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Idioma__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Importe_Concedido__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Importe_Concedido__c</fullName>
    <label>Importe Concedido</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Importe_solicitado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Importe_solicitado__c</fullName>
    <label>Importe solicitado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3.000</fullName>
            </value>
            <value>
                <fullName>6.000</fullName>
            </value>
            <value>
                <fullName>12.000</fullName>
            </value>
            <value>
                <fullName>30.000</fullName>
            </value>
            <value>
                <fullName>60.000</fullName>
            </value>
            <value>
                <fullName>120.000</fullName>
            </value>
            <value>
                <fullName>500.000</fullName>
            </value>
            <value>
                <fullName>1.000.000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Terminos_de_pago__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Terminos_de_pago__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Términos de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Terminos_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Exp_CYC__c</fullName>
    <label>Fecha Expediente CYC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_Contable_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Grupo_Contable_Cliente__c</fullName>
    <label>Grupo Contable Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_Contable_Cliente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_contable_negocio__c.field-meta.xml
<CustomField>
    <fullName>Grupo_contable_negocio__c</fullName>
    <label>Grupo contable negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_registro_IVA_negocio__c.field-meta.xml
<CustomField>
    <fullName>Grupo_registro_IVA_negocio__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Grupo registro IVA negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_registro_IVA_negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Limite_Credito_CYC__c.field-meta.xml
<CustomField>
    <fullName>Limite_Credito_CYC__c</fullName>
    <label>Límite de crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Num_Exp_CYC__c</fullName>
    <label>Núm. Exped. CYC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>Numero_cliente_ERP__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente ERP</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/ERUM_Direcciones_Envio__c.object-meta.xml
<CustomObject>
    <label>Direcciones Envio</label>
    <nameField>
        <label>Nombre Dirección</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direcciones Envio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Activa_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Activa_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si está marcado indica que el ERP ha confirmado que la Dirección se ha podido crear en su sistema.</description>
    <label>Activa ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Calle__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Calle__c</fullName>
    <label>Calle</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Ciudad__c</fullName>
    <label>Ciudad</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Cod_de_Direccion_NAV__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cod_de_Direccion_NAV__c</fullName>
    <externalId>true</externalId>
    <label>Cód de Dirección NAV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Codigo_postal__c</fullName>
    <label>Código postal</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Country_RegionCOD__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Country_RegionCOD__c</fullName>
    <label>ISO Cod. Region</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Direccion_Principal_Envio__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Direccion_Principal_Envio__c</fullName>
    <defaultValue>false</defaultValue>
    <description>si está marcado significa que es la direccion principal de envio</description>
    <label>Dirección Principal Envío</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Fecha_Activa_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Activa_ERP__c</fullName>
    <label>Fecha Activa ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Nombre_comercial__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Nombre_comercial__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nombre comercial</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Direcciones Envio</relationshipLabel>
    <relationshipName>Direcciones_Envio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Num_de_Direccion_NAV__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Num_de_Direccion_NAV__c</fullName>
    <displayFormat>SF{00000000}</displayFormat>
    <externalId>true</externalId>
    <label>ERUM_Num_de_Direccion_NAV</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Pais__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Pais__c</fullName>
    <label>País</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/Numero_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>Numero_cliente_ERP__c</fullName>
    <formula>ERUM_Nombre_comercial__r.Numero_cliente_ERP__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número cliente ERP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Activo_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Calle__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Calle__c</fullName>
    <formula>ERUM_Nombre_Direccion__r.ERUM_Calle__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calle</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Ciudad__c</fullName>
    <formula>ERUM_Nombre_Direccion__r.ERUM_Ciudad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ciudad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Codigo_postal__c</fullName>
    <formula>ERUM_Nombre_Direccion__r.ERUM_Codigo_postal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código postal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Fecha_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Activo_ERP__c</fullName>
    <label>Fecha Activo ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Forma_de_pago__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Forma_de_pago__c</fullName>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Forma_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Idioma__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Idioma__c</fullName>
    <formula>TEXT(Account.ERUM_Idioma__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Idioma</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Nombre_Direccion__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Nombre_Direccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre Dirección</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ERUM_Direcciones_Envio__c.ERUM_Nombre_comercial__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ERUM_Direcciones_Envio__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Pais__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Pais__c</fullName>
    <formula>ERUM_Nombre_Direccion__r.ERUM_Pais__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Terminos_de_pago__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Terminos_de_pago__c</fullName>
    <label>Términos de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Terminos_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Pedido.recordType-meta.xml
<RecordType>
    <fullName>Pedido</fullName>
    <active>true</active>
    <businessProcess>Pedido</businessProcess>
    <label>Pedido</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/ERUM_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Activo_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ERUM_Activo_ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ERUM_Impuesto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Impuesto__c</fullName>
    <defaultValue>21/100</defaultValue>
    <label>Impuesto (%)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ERUM_UM__c.field-meta.xml
<CustomField>
    <fullName>ERUM_UM__c</fullName>
    <label>Unidad medida venta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Grupo_contable_negocio__c.field-meta.xml
<CustomField>
    <fullName>Grupo_contable_negocio__c</fullName>
    <label>Grupo contable negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ERUM_Estado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nuevo</fullName>
    </customValue>
    <customValue>
        <fullName>En Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Fin de Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Convertido</fullName>
    </customValue>
    <customValue>
        <fullName>Activo</fullName>
    </customValue>
    <customValue>
        <fullName>Inactivo</fullName>
    </customValue>
    <customValue>
        <fullName>Pausado</fullName>
    </customValue>
    <masterLabel>Estado</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ERUM_Terminos_de_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <label>0 DIAS</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 DIAS</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15 DIAS</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30 DIAS</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>35 DIAS</label>
    </customValue>
    <customValue>
        <fullName>45</fullName>
        <label>45 DIAS</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
        <label>50 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>60 DIAS</label>
    </customValue>
    <customValue>
        <fullName>70</fullName>
        <label>70 DIAS</label>
    </customValue>
    <customValue>
        <fullName>75</fullName>
        <label>75 DIAS</label>
    </customValue>
    <customValue>
        <fullName>85</fullName>
        <label>85 DIAS</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>150</fullName>
        <label>150 DIAS</label>
    </customValue>
    <customValue>
        <fullName>180</fullName>
        <label>180 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30-70% ADV</fullName>
        <label>30% in advance 70% against BL copy</label>
    </customValue>
    <customValue>
        <fullName>50-50%</fullName>
        <label>50% Advance / 50% Loaded</label>
    </customValue>
    <customValue>
        <fullName>50% 50%</fullName>
        <label>50%TT in advance / 50%, 30 days TT date invoice</label>
    </customValue>
    <customValue>
        <fullName>100%ADVANC</fullName>
        <label>100% Advance</label>
    </customValue>
    <customValue>
        <fullName>30-60</fullName>
        <label>2PLAZ 60 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60-90</fullName>
        <label>2PLAZ 90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>90-120</fullName>
        <label>2PLAZ 120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30-60-90</fullName>
        <label>3PLAZ 90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60-90-120</fullName>
        <label>3PLAZ 120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>ZARA</fullName>
        <label>Zara</label>
    </customValue>
    <masterLabel>Términos de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Forma_de_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CONF</fullName>
        <label>Confirming</label>
    </customValue>
    <customValue>
        <fullName>DOM</fullName>
        <label>Recibo domiciliado</label>
    </customValue>
    <customValue>
        <fullName>GIR</fullName>
        <label>Giro</label>
    </customValue>
    <customValue>
        <fullName>GRU</fullName>
        <label>Empresas vinculadas grupo</label>
    </customValue>
    <customValue>
        <fullName>PAG</fullName>
        <label>Pagaré</label>
    </customValue>
    <customValue>
        <fullName>PAG-E</fullName>
        <label>Pagaré emitido proveedores</label>
    </customValue>
    <customValue>
        <fullName>RCONF</fullName>
        <label>RECIBIDO CONFIRMING</label>
    </customValue>
    <customValue>
        <fullName>TRF</fullName>
        <label>Transferencia</label>
    </customValue>
    <customValue>
        <fullName>TRFBKINUSD</fullName>
        <label>Transferencia USD</label>
    </customValue>
    <customValue>
        <fullName>TRFBNK</fullName>
        <label>Transferencia Bankinter</label>
    </customValue>
    <masterLabel>Forma de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_Contable_Cliente.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GCGNA</fullName>
        <label>Nac. del Grupo - Grupo Clientes</label>
    </customValue>
    <customValue>
        <fullName>GCGRM</fullName>
        <label>RM del Grupo - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCGUE</fullName>
        <label>UE del Grupo - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCNA</fullName>
        <label>Nacional - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
        <label>Resto Mundo - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCUE</fullName>
        <label>UE - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GDUE</fullName>
        <isActive>false</isActive>
        <label>GDUE</label>
    </customValue>
    <customValue>
        <fullName>GDRM</fullName>
        <isActive>false</isActive>
        <label>GDRM</label>
    </customValue>
    <customValue>
        <fullName>GDNA</fullName>
        <isActive>false</isActive>
        <label>GDNA</label>
    </customValue>
    <customValue>
        <fullName>GCDCUE</fullName>
        <isActive>false</isActive>
        <label>GCDCUE</label>
    </customValue>
    <customValue>
        <fullName>GCDCRM</fullName>
        <isActive>false</isActive>
        <label>GCDCRM</label>
    </customValue>
    <customValue>
        <fullName>GCDCNA</fullName>
        <isActive>false</isActive>
        <label>GCDCNA</label>
    </customValue>
    <masterLabel>Grupo Contable Cliente</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_negocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EXPORT</fullName>
        <label>Otros clientes y proveedores (no UE)</label>
    </customValue>
    <customValue>
        <fullName>NAC</fullName>
        <label>Clientes y proveedores nacionales</label>
    </customValue>
    <customValue>
        <fullName>UE</fullName>
        <label>Clientes y proveedores UE</label>
    </customValue>
    <customValue>
        <fullName>INTERCOMP</fullName>
        <isActive>false</isActive>
        <label>Intercompany</label>
    </customValue>
    <masterLabel>Grupo contable negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Idioma.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ESP</fullName>
        <label>Español</label>
    </customValue>
    <customValue>
        <fullName>ENG</fullName>
        <label>Inglés</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <label>Francés</label>
    </customValue>
    <customValue>
        <fullName>DEU</fullName>
        <label>Alemán</label>
    </customValue>
    <customValue>
        <fullName>PTG</fullName>
        <label>Portugués</label>
    </customValue>
    <customValue>
        <fullName>ITA</fullName>
        <label>Italiano</label>
    </customValue>
    <masterLabel>Idioma</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TrgOpportunityController.cls
public with sharing class TrgOpportunityController {

    Map<Id, Opportunity> newOpps = new Map<Id, Opportunity>();
    Map<Id, Opportunity> oldOpps = new Map<Id, Opportunity>();

    public TrgOpportunityController() {

        newOpps = (Map<Id, Opportunity>) Trigger.newMap;
        oldOpps = (Map<Id, Opportunity>) Trigger.oldMap;

        Map<Id, Schema.RecordTypeInfo> recordTypeInfoMap = Schema.SObjectType.Opportunity.getRecordTypeInfosById();
        
        Map<Id, Account> accsToInsert = new Map<Id, Account>();
        Map<Id, ERUM_Direcciones_Envio__c> dirsToInsert = new Map<Id, ERUM_Direcciones_Envio__c>();
        Map<Id, Opportunity> oppsToInsert = new Map<Id, Opportunity>();
        Map<Id, Opportunity> oppsToUpdate = new Map<Id, Opportunity>();
        Map<Id, List<OpportunityLineItem>> linesToInsert = new Map<Id, List<OpportunityLineItem>>();
        Map<Id, List<OpportunityLineItem>> linesToUpdate = new Map<Id, List<OpportunityLineItem>>();
        List<OpportunityLineItem> oppItemsListInsert = new List<OpportunityLineItem>();
        List<OpportunityLineItem> oppItemsListUpdate = new List<OpportunityLineItem>();
        
        List<Id> accountIds = new List<Id>();
        List<Id> dirIds = new List<Id>();
        for (Opportunity newOpp : newOpps.values()) {
            accountIds.add(newOpp.AccountId);
            dirIds.add(newOpp.ERUM_Nombre_Direccion__c);
        }

        Map<String, Schema.RecordTypeInfo> recordTypeInfoMapAccount = Schema.SObjectType.Account.getRecordTypeInfosByName();
        List<Account> accounts = new List<Account>();
        accounts = [
            SELECT Id, ERUM_Estado__c, Name, ERUM_CIF_Europeo__c, Website, Phone, ERUM_Email__c, ERUM_Idioma__c, CurrencyIsoCode, IBAN__c, BillingStreet, BillingPostalCode, BillingCountry, ERUM_Terminos_de_pago__c, ERUM_Forma_de_pago__c, Grupo_Contable_Cliente__c, Grupo_contable_negocio__c, Grupo_registro_IVA_negocio__c, Num_Exp_CYC__c, Fecha_Exp_CYC__c, Dias_Asegurado_CYC__c, Limite_Credito_CYC__c, Clasificacion__c, ERUM_Importe_Concedido__c, ERUM_Importe_solicitado__c, ERUM_Codigo_cliente_ERP__c, Numero_cliente_ERP__c, ERUM_Activo_ERP__c, ERUM_Fecha_Activo_ERP__c
            FROM Account 
            WHERE Id IN: accountIds
        ];
        Map<Id, Account> accountMap = new Map<Id, Account>();
        for (Account acc : accounts) {
            if (!accountMap.containsKey(acc.Id)) {
                accountMap.put(acc.Id, acc);
            }
        }

        List<ERUM_Direcciones_Envio__c> dirs = new List<ERUM_Direcciones_Envio__c>();
        dirs = [
            SELECT Id, ERUM_Nombre_comercial__c, ERUM_Num_de_Direccion_NAV__c, Name, ERUM_Calle__c, ERUM_Ciudad__c, ERUM_Codigo_postal__c, ERUM_Pais__c, ERUM_Country_RegionCOD__c, ERUM_Direccion_Principal_Envio__c, ERUM_Cod_de_Direccion_NAV__c, ERUM_Activa_ERP__c, ERUM_Fecha_Activa_ERP__c
            FROM ERUM_Direcciones_Envio__c
            WHERE Id IN: dirIds
        ];
        Map<Id, ERUM_Direcciones_Envio__c> dirMap = new Map<Id, ERUM_Direcciones_Envio__c>();
        for (ERUM_Direcciones_Envio__c dir : dirs) {
            if (!dirMap.containsKey(dir.Id)) {
                dirMap.put(dir.Id, dir);
            }
        }

        if (Trigger.isAfter && Trigger.isInsert) {
            for (Opportunity newOpp : newOpps.values()) {

                Account oppAccount = accountMap.get(newOpp.AccountId);
                ERUM_Direcciones_Envio__c oppDireccion = dirMap.get(newOpp.ERUM_Nombre_Direccion__c);

                if (oppAccount != null && oppDireccion != null && newOpp.RecordTypeId != null) {
                    
                    if (recordTypeInfoMap.get(newOpp.RecordTypeId).getName() == 'Pedido') {
                        
                        oppItemsListInsert = [
                            SELECT Id, TotalPrice, ERUM_Impuesto__c, ListPrice, ProductCode, Quantity, ServiceDate, Discount, ERUM_UM__c, Description, ERUM_Cantidad_entregada__c, ERUM_Activo_ERP__c, Opportunity.ERUM_Offer_Id_External__c, OpportunityId, Erum_Key_Linea__c, ERUM_Line_No__c, Opportunity.AccountId, Opportunity.Account.Numero_cliente_ERP__c, Product2.ERUM_External_ProductCode__c, Tarifa__c, UnitPrice
                            FROM OpportunityLineItem 
                            WHERE OpportunityId =: newOpp.Id AND ERUM_Activo_ERP__c =: false
                        ];

                        oppItemsListUpdate = [
                            SELECT Id, TotalPrice, ERUM_Impuesto__c, ListPrice, ProductCode, Quantity, ServiceDate, Discount, ERUM_UM__c, Description, ERUM_Cantidad_entregada__c, ERUM_Activo_ERP__c, Opportunity.ERUM_Offer_Id_External__c, OpportunityId, Erum_Key_Linea__c, ERUM_Line_No__c, Opportunity.AccountId, Opportunity.Account.Numero_cliente_ERP__c, Product2.ERUM_External_ProductCode__c, Tarifa__c, UnitPrice
                            FROM OpportunityLineItem 
                            WHERE OpportunityId =: newOpp.Id AND ERUM_Activo_ERP__c =: true
                        ];

                        if (String.isBlank(oppAccount.Numero_cliente_ERP__c)) {
                            accsToInsert.put(oppAccount.Id, oppAccount);
                        }

                        if (!oppDireccion.ERUM_Activa_ERP__c) {
                            dirsToInsert.put(oppDireccion.Id, oppDireccion);
                        }

                        oppsToInsert.put(newOpp.Id, newOpp);

                        if (oppItemsListInsert.size() > 0) {
                            linesToInsert.put(newOpp.Id, oppItemsListInsert);
                        }

                        if (oppItemsListUpdate.size() > 0) {
                            linesToUpdate.put(newOpp.Id, oppItemsListUpdate);
                        }
                    }
                }
            }
        }

        if (Trigger.isAfter && Trigger.isUpdate) {
            for (Opportunity newOpp : newOpps.values()) {

                Account oppAccount = accountMap.get(newOpp.AccountId);
                ERUM_Direcciones_Envio__c oppDireccion = dirMap.get(newOpp.ERUM_Nombre_Direccion__c);
                Opportunity oldOpp = oldOpps.get(newOpp.Id);

                if (oppAccount != null && oppDireccion != null && newOpp.RecordTypeId != null) {
                    
                    if (recordTypeInfoMap.get(newOpp.RecordTypeId).getName() == 'Pedido') {
                        
                        oppItemsListInsert = [
                            SELECT Id, TotalPrice, ERUM_Impuesto__c, ListPrice, ProductCode, Quantity, ServiceDate, Discount, ERUM_UM__c, Description, ERUM_Cantidad_entregada__c, ERUM_Activo_ERP__c, Opportunity.ERUM_Offer_Id_External__c, OpportunityId, Erum_Key_Linea__c, ERUM_Line_No__c, Opportunity.AccountId, Opportunity.Account.Numero_cliente_ERP__c, Product2.ERUM_External_ProductCode__c, Tarifa__c, UnitPrice
                            FROM OpportunityLineItem 
                            WHERE OpportunityId =: newOpp.Id AND ERUM_Activo_ERP__c =: false
                        ];

                        oppItemsListUpdate = [
                            SELECT Id, TotalPrice, ERUM_Impuesto__c, ListPrice, ProductCode, Quantity, ServiceDate, Discount, ERUM_UM__c, Description, ERUM_Cantidad_entregada__c, ERUM_Activo_ERP__c, Opportunity.ERUM_Offer_Id_External__c, OpportunityId, Erum_Key_Linea__c, ERUM_Line_No__c, Opportunity.AccountId, Opportunity.Account.Numero_cliente_ERP__c, Product2.ERUM_External_ProductCode__c, Tarifa__c, UnitPrice
                            FROM OpportunityLineItem 
                            WHERE OpportunityId =: newOpp.Id AND ERUM_Activo_ERP__c =: true
                        ];

                        if (String.isBlank(oppAccount.Numero_cliente_ERP__c)) {
                            accsToInsert.put(oppAccount.Id, oppAccount);
                        }

                        if (!oppDireccion.ERUM_Activa_ERP__c) {
                            dirsToInsert.put(oppDireccion.Id, oppDireccion);
                        }

                        if (!newOpp.ERUM_Activo_ERP__c) {
                            oppsToInsert.put(newOpp.Id, newOpp);
                        } else {
                            oppsToUpdate.put(newOpp.Id, newOpp);
                        }
                        
                        if (oppItemsListInsert.size() > 0) {
                            System.debug(Opportunity.ERUM_Offer_Id_External__c);
                            linesToInsert.put(newOpp.Id, oppItemsListInsert);
                        }

                        if (oppItemsListUpdate.size() > 0) {
                            System.debug(Opportunity.ERUM_Offer_Id_External__c);
                            linesToUpdate.put(newOpp.Id, oppItemsListUpdate);
                        }
                    }
                }
            }
        }

        System.debug(oppsToInsert);
        System.debug(oppsToUpdate);

        if (oppsToInsert.size() > 0 || oppsToUpdate.size() > 0) {
            Id jobId1 = System.enqueueJob(new QueueableOpportunity(accsToInsert, dirsToInsert, oppsToInsert, oppsToUpdate, linesToInsert, linesToUpdate));
            System.debug(jobId1);
        }
    }

    /**
     * ¿POR QUÉ QUEUABLE? 
     * LAS LÍNEAS DEPENDEN DE UNA CABECERA PARA PODER PASAR AL ERP. LOS MÉTODOS @FUTURE AL SER ASÍNCRONOS NO PUEDEN GARANTIZAR EL ORDEN DE EJECUCIÓN. UN QUEUABLE SÍ PUEDE.
     * NO DEBE OLVIDAR LA IMPLEMENTACIÓN A DATABASE.ALLOWSCALLOUTS PARA PODER REALIZAR LLAMADAS HTTP.
     */
    public class QueueableOpportunity implements Queueable, Database.AllowsCallouts {

        private Map<Id, Account> accsToInsert;
        private Map<Id, ERUM_Direcciones_Envio__c> dirsToInsert;
        private Map<Id, Opportunity> oppsToInsert;
        private Map<Id, Opportunity> oppsToUpdate;
        private Map<Id, List<OpportunityLineItem>> linesToInsert;
        private Map<Id, List<OpportunityLineItem>> linesToUpdate;

        public QueueableOpportunity(Map<Id, Account> accsToInsert_x, Map<Id, ERUM_Direcciones_Envio__c> dirsToInsert_x, Map<Id, Opportunity> oppsToInsert_x, Map<Id, Opportunity> oppsToUpdate_x, Map<Id, List<OpportunityLineItem>> linesToInsert_x, Map<Id, List<OpportunityLineItem>> linesToUpdate_x) {
            this.accsToInsert = accsToInsert_x;
            this.dirsToInsert = dirsToInsert_x;
            this.oppsToInsert = oppsToInsert_x;
            this.oppsToUpdate = oppsToUpdate_x;
            this.linesToInsert = linesToInsert_x;
            this.linesToUpdate = linesToUpdate_x;
        }

        public void execute(System.QueueableContext context) {
            if (accsToInsert.size() > 0) {
                WSAccount.insertAccount(JSON.serialize(accsToInsert));
            }
            Id jobId2 = Test.isRunningTest() ? null : System.enqueueJob(new WSQueueableOpp.QueueableDireccionInsert(dirsToInsert, oppsToInsert, oppsToUpdate, linesToInsert, linesToUpdate));
            System.debug(jobId2);
        }
    }
    
}