force-app/main/default/objects/Account/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asegurado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dias_Asegurado_CYC__c.field-meta.xml
<CustomField>
    <fullName>Dias_Asegurado_CYC__c</fullName>
    <label>Días asegurado CYC</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Activo_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_CIF_Europeo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_CIF_Europeo__c</fullName>
    <label>CIF Europeo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Codigo_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Codigo_cliente_ERP__c</fullName>
    <externalId>true</externalId>
    <label>Código cliente ERP</label>
    <length>225</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Codigo_SWIFT__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Codigo_SWIFT__c</fullName>
    <label>Código SWIFT</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Comercial_asignado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Comercial_asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comercial asignado</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Email__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Estado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Estado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Fecha_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Activo_ERP__c</fullName>
    <label>Fecha Activo ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Forma_de_pago__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Forma_de_pago__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Forma_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Idioma__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Importe_Concedido__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Importe_Concedido__c</fullName>
    <label>Importe Concedido</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Importe_solicitado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Importe_solicitado__c</fullName>
    <label>Importe solicitado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3.000</fullName>
            </value>
            <value>
                <fullName>6.000</fullName>
            </value>
            <value>
                <fullName>12.000</fullName>
            </value>
            <value>
                <fullName>30.000</fullName>
            </value>
            <value>
                <fullName>60.000</fullName>
            </value>
            <value>
                <fullName>120.000</fullName>
            </value>
            <value>
                <fullName>500.000</fullName>
            </value>
            <value>
                <fullName>1.000.000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Numero_de_cuenta__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Numero_de_cuenta__c</fullName>
    <label>Nº de cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Terminos_de_pago__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Terminos_de_pago__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Términos de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Terminos_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Exp_CYC__c</fullName>
    <label>Fecha Expediente CYC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_Contable_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Grupo_Contable_Cliente__c</fullName>
    <label>Grupo Contable Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_Contable_Cliente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_contable_negocio__c.field-meta.xml
<CustomField>
    <fullName>Grupo_contable_negocio__c</fullName>
    <label>Grupo contable negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_registro_IVA_negocio__c.field-meta.xml
<CustomField>
    <fullName>Grupo_registro_IVA_negocio__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Grupo registro IVA negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_registro_IVA_negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Limite_Credito_CYC__c.field-meta.xml
<CustomField>
    <fullName>Limite_Credito_CYC__c</fullName>
    <label>Límite de crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Num_Exp_CYC__c</fullName>
    <label>Núm. Exped. CYC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>Numero_cliente_ERP__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente ERP</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/ERUM_Estado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nuevo</fullName>
    </customValue>
    <customValue>
        <fullName>En Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Fin de Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Convertido</fullName>
    </customValue>
    <customValue>
        <fullName>Activo</fullName>
    </customValue>
    <customValue>
        <fullName>Inactivo</fullName>
    </customValue>
    <customValue>
        <fullName>Pausado</fullName>
    </customValue>
    <masterLabel>Estado</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ERUM_Terminos_de_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <label>0 DIAS</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 DIAS</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15 DIAS</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30 DIAS</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>35 DIAS</label>
    </customValue>
    <customValue>
        <fullName>45</fullName>
        <label>45 DIAS</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
        <label>50 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>60 DIAS</label>
    </customValue>
    <customValue>
        <fullName>70</fullName>
        <label>70 DIAS</label>
    </customValue>
    <customValue>
        <fullName>75</fullName>
        <label>75 DIAS</label>
    </customValue>
    <customValue>
        <fullName>85</fullName>
        <label>85 DIAS</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>150</fullName>
        <label>150 DIAS</label>
    </customValue>
    <customValue>
        <fullName>180</fullName>
        <label>180 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30-70% ADV</fullName>
        <label>30% in advance 70% against BL copy</label>
    </customValue>
    <customValue>
        <fullName>50-50%</fullName>
        <label>50% Advance / 50% Loaded</label>
    </customValue>
    <customValue>
        <fullName>50% 50%</fullName>
        <label>50%TT in advance / 50%, 30 days TT date invoice</label>
    </customValue>
    <customValue>
        <fullName>100%ADVANC</fullName>
        <label>100% Advance</label>
    </customValue>
    <customValue>
        <fullName>30-60</fullName>
        <label>2PLAZ 60 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60-90</fullName>
        <label>2PLAZ 90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>90-120</fullName>
        <label>2PLAZ 120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30-60-90</fullName>
        <label>3PLAZ 90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60-90-120</fullName>
        <label>3PLAZ 120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>ZARA</fullName>
        <label>Zara</label>
    </customValue>
    <masterLabel>Términos de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Forma_de_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CONF</fullName>
        <label>Confirming</label>
    </customValue>
    <customValue>
        <fullName>DOM</fullName>
        <label>Recibo domiciliado</label>
    </customValue>
    <customValue>
        <fullName>GIR</fullName>
        <label>Giro</label>
    </customValue>
    <customValue>
        <fullName>GRU</fullName>
        <label>Empresas vinculadas grupo</label>
    </customValue>
    <customValue>
        <fullName>PAG</fullName>
        <label>Pagaré</label>
    </customValue>
    <customValue>
        <fullName>PAG-E</fullName>
        <label>Pagaré emitido proveedores</label>
    </customValue>
    <customValue>
        <fullName>RCONF</fullName>
        <label>RECIBIDO CONFIRMING</label>
    </customValue>
    <customValue>
        <fullName>TRF</fullName>
        <label>Transferencia</label>
    </customValue>
    <customValue>
        <fullName>TRFBKINUSD</fullName>
        <label>Transferencia USD</label>
    </customValue>
    <customValue>
        <fullName>TRFBNK</fullName>
        <label>Transferencia Bankinter</label>
    </customValue>
    <masterLabel>Forma de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_Contable_Cliente.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GCGNA</fullName>
        <label>Nac. del Grupo - Grupo Clientes</label>
    </customValue>
    <customValue>
        <fullName>GCGRM</fullName>
        <label>RM del Grupo - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCGUE</fullName>
        <label>UE del Grupo - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCNA</fullName>
        <label>Nacional - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
        <label>Resto Mundo - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCUE</fullName>
        <label>UE - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GDUE</fullName>
        <isActive>false</isActive>
        <label>GDUE</label>
    </customValue>
    <customValue>
        <fullName>GDRM</fullName>
        <isActive>false</isActive>
        <label>GDRM</label>
    </customValue>
    <customValue>
        <fullName>GDNA</fullName>
        <isActive>false</isActive>
        <label>GDNA</label>
    </customValue>
    <customValue>
        <fullName>GCDCUE</fullName>
        <isActive>false</isActive>
        <label>GCDCUE</label>
    </customValue>
    <customValue>
        <fullName>GCDCRM</fullName>
        <isActive>false</isActive>
        <label>GCDCRM</label>
    </customValue>
    <customValue>
        <fullName>GCDCNA</fullName>
        <isActive>false</isActive>
        <label>GCDCNA</label>
    </customValue>
    <masterLabel>Grupo Contable Cliente</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_negocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EXPORT</fullName>
        <label>Otros clientes y proveedores (no UE)</label>
    </customValue>
    <customValue>
        <fullName>NAC</fullName>
        <label>Clientes y proveedores nacionales</label>
    </customValue>
    <customValue>
        <fullName>UE</fullName>
        <label>Clientes y proveedores UE</label>
    </customValue>
    <customValue>
        <fullName>INTERCOMP</fullName>
        <isActive>false</isActive>
        <label>Intercompany</label>
    </customValue>
    <masterLabel>Grupo contable negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Idioma.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ESP</fullName>
        <label>Español</label>
    </customValue>
    <customValue>
        <fullName>ENG</fullName>
        <label>Inglés</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <label>Francés</label>
    </customValue>
    <customValue>
        <fullName>DEU</fullName>
        <label>Alemán</label>
    </customValue>
    <customValue>
        <fullName>PTG</fullName>
        <label>Portugués</label>
    </customValue>
    <customValue>
        <fullName>ITA</fullName>
        <label>Italiano</label>
    </customValue>
    <masterLabel>Idioma</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WSAccount.cls
public with sharing class WSAccount {

    public static void insertAccount(String accountsJSON) {

        Map<Id, Account> accounts = (Map<Id, Account>) JSON.deserialize(accountsJSON, (Map<Id, Account>.class));

        AitanaAccountWS.wsSF_Clientes_Port clientesPort = new AitanaAccountWS.wsSF_Clientes_Port();
        clientesPort.inputHttpHeaders_x = new Map<String, String>();
        clientesPort.outputHttpHeaders_x = new Map<String, String>();
        clientesPort.inputHttpHeaders_x.put('Authorization', 'Basic RVJVTUdST1VQXE5BVkRFVjozYVlySmxLcDZKTWZUM2lsNUJWZmoxQXBMTGFCYU9WM0RyR0RTb21qUThvPQ==');
        clientesPort.inputHttpHeaders_x.put('Content-Type', 'text/xml');
        clientesPort.inputHttpHeaders_x.put('SOAPAction', 'POST');
        clientesPort.inputHttpHeaders_x.put('Accept', '*/*');
        clientesPort.inputHttpHeaders_x.put('Accept-Encoding', 'gzip, deflate, br');
        clientesPort.inputHttpHeaders_x.put('Connection', 'keep-alive');
        clientesPort.outputHttpHeaders_x.put('Content-Type', 'text/xml; charset=utf-8');
        clientesPort.outputHttpHeaders_x.put('Server', 'Microsoft-HTTPAPI/2.0');

        AitanaAccountWS.wsSF_Clientes_List clientesList = new AitanaAccountWS.wsSF_Clientes_List();
        List<AitanaAccountWS.wsSF_Clientes> clientes = new List<AitanaAccountWS.wsSF_Clientes>();
        for (Account account_x : accounts.values()) {
            AitanaAccountWS.wsSF_Clientes cliente = new AitanaAccountWS.wsSF_Clientes();
            cliente.Blocked = account_x.ERUM_Estado__c == 'Activo' || account_x.ERUM_Estado__c == 'Nuevo' ? '_blank_' : 'All';
            cliente.Name = account_x.Name;
            cliente.VAT_Registration_No = account_x.ERUM_CIF_Europeo__c;
            cliente.Home_Page = account_x.Website;
            cliente.Phone_No = account_x.Phone;
            cliente.E_Mail = account_x.ERUM_Email__c;
            cliente.Language_Code = account_x.ERUM_Idioma__c;
            cliente.Currency_Code = account_x.CurrencyIsoCode == 'EUR' ?  null : account_x.CurrencyIsoCode;
            cliente.Salesperson_Code = 'IRENE'; // account_x.ERUM_Comercial_asignado__c;
            cliente.vCCC_No = account_x.ERUM_Numero_de_cuenta__c;
            cliente.vSWIFT_Code = account_x.ERUM_Codigo_SWIFT__c;
            cliente.vIBAN = account_x.IBAN__c;
            cliente.Tipo_de_cliente = '_blank_';
            if (account_x.BillingStreet != null) {
                cliente.Address = account_x.BillingStreet.length() > 50 ? account_x.BillingStreet.substring(0, 50) : account_x.BillingStreet;
                cliente.Address_2 = account_x.BillingStreet.length() > 50 ? account_x.BillingStreet.substring(51, account_x.BillingStreet.length()) : null;
            }
            if (account_x.BillingPostalCode != null && account_x.BillingCountry != null) {
                cliente.Post_Code = account_x.BillingPostalCode.startsWith(account_x.BillingCountry + '-') ? account_x.BillingPostalCode : account_x.BillingCountry + '-' + account_x.BillingPostalCode;
            }
            cliente.Payment_Terms_Code = account_x.ERUM_Terminos_de_pago__c;
            cliente.Payment_Method_Code = account_x.ERUM_Forma_de_pago__c;
            cliente.Customer_Posting_Group = account_x.Grupo_Contable_Cliente__c;
            cliente.Gen_Bus_Posting_Group = account_x.Grupo_contable_negocio__c;
            cliente.VAT_Bus_Posting_Group = account_x.Grupo_registro_IVA_negocio__c;
            cliente.vNumSuplemento = account_x.Num_Exp_CYC__c;
            DateTime vFechaExpedienteDt = account_x.Fecha_Exp_CYC__c != null ? DateTime.newInstance(account_x.Fecha_Exp_CYC__c.year(), account_x.Fecha_Exp_CYC__c.month(),account_x.Fecha_Exp_CYC__c.day()) : null;
            String vFechaExpedienteStr = vFechaExpedienteDt != null ? vFechaExpedienteDt.format('yyyy-MM-dd') : null;
            cliente.vFechaExpediente = vFechaExpedienteStr;
            System.debug('cliente.vFechaExpediente: ' + cliente.vFechaExpediente);
            cliente.Dias_Asegurado_CYC = String.valueOf(account_x.Dias_Asegurado_CYC__c);
            cliente.Credit_Limit_LCY = String.valueOf(account_x.Limite_Credito_CYC__c);
            cliente.vClasificacion = account_x.Clasificacion__c != null ? account_x.Clasificacion__c.toUpperCase() : null;
            cliente.vImporteConcedido = String.valueOf(account_x.ERUM_Importe_Concedido__c);
            cliente.vImporteSolicitado = account_x.ERUM_Importe_solicitado__c != null ? account_x.ERUM_Importe_solicitado__c.replace('.', '') : null;
            System.debug('cliente.vImporteConcedido: ' + cliente.vImporteConcedido);
            System.debug('cliente.vImporteSolicitado: ' + cliente.vImporteSolicitado);
            DateTime vFechaVtoDt = account_x.Fecha_Exp_CYC__c != null ? DateTime.newInstance(account_x.Fecha_Exp_CYC__c.year() + 1, account_x.Fecha_Exp_CYC__c.month(),account_x.Fecha_Exp_CYC__c.day()) : null;
            String vFechaVtoStr = vFechaVtoDt != null ? vFechaVtoDt.format('yyyy-MM-dd') : null;
            cliente.vFechaVto = vFechaVtoStr;
            System.debug('cliente.vFechaVto: ' + cliente.vFechaVto);
            clientes.add(cliente);
        }

        clientesList.wsSF_Clientes = clientes;
        List<AitanaAccountWS.wsSF_Clientes> wsSF_ClientesResponse = new List<AitanaAccountWS.wsSF_Clientes>();
        try {
            wsSF_ClientesResponse = clientesPort.CreateMultiple(clientesList).wsSF_Clientes;
        } catch (CalloutException cEx) {
            System.debug('Excepción producida al crear cuentas en el ERP: ' + cEx.getMessage());
            GestionErrores.insertGestionErrores(cEx.getMessage(), 'Salesforce', null, accounts.values()[0].Id, null, 'Clientes');
            return;
        }
        
        if (wsSF_ClientesResponse.size() > 0) {
            Map<String, AitanaAccountWS.wsSF_Clientes> insertedClientes = new Map<String, AitanaAccountWS.wsSF_Clientes>();
            for (AitanaAccountWS.wsSF_Clientes cliente : wsSF_ClientesResponse) {
                insertedClientes.put(cliente.VAT_Registration_No, cliente);
            }
            for (Account account : accounts.values()) {
                Account newInstanceOfAccount = new Account(
                    Id = account.Id,
                    ERUM_Codigo_cliente_ERP__c = insertedClientes.get(account.ERUM_CIF_Europeo__c).Key,
                    Numero_cliente_ERP__c = insertedClientes.get(account.ERUM_CIF_Europeo__c).No,
                    ERUM_Activo_ERP__c = true,
                    ERUM_Fecha_Activo_ERP__c = System.today()
                );
                try {
                    TrgController.setDoNotRunTrigger();
                    Database.update(newInstanceOfAccount, true);
                } catch (DmlException dmlEx) {
                    System.debug('Excepción producida al traer de vuelta el id de la cuenta en la inserción: ' + dmlEx.getMessage());
                    GestionErrores.insertGestionErrores(dmlEx.getMessage(), 'Salesforce', null, account.Id, null, 'Clientes');
                    return;
                }
            }
        }
        
    }

    public static void updateAccount(String accountsJSON) {

        Map<Id, Account> accounts = (Map<Id, Account>) JSON.deserialize(accountsJSON, (Map<Id, Account>.class));

        AitanaAccountWS.wsSF_Clientes_Port clientesPort = new AitanaAccountWS.wsSF_Clientes_Port();
        clientesPort.inputHttpHeaders_x = new Map<String, String>();
        clientesPort.inputHttpHeaders_x.put('Authorization', 'Basic RVJVTUdST1VQXE5BVkRFVjozYVlySmxLcDZKTWZUM2lsNUJWZmoxQXBMTGFCYU9WM0RyR0RTb21qUThvPQ==');
        clientesPort.inputHttpHeaders_x.put('Content-Type', 'text/xml');
        clientesPort.inputHttpHeaders_x.put('SOAPAction', 'POST');
        clientesPort.inputHttpHeaders_x.put('Accept', '*/*');
        clientesPort.inputHttpHeaders_x.put('Accept-Encoding', 'gzip, deflate, br');
        clientesPort.inputHttpHeaders_x.put('Connection', 'keep-alive');
        clientesPort.outputHttpHeaders_x = new Map<String, String>();
        clientesPort.outputHttpHeaders_x.put('Content-Type', 'text/xml; charset=utf-8');
        clientesPort.outputHttpHeaders_x.put('Server', 'Microsoft-HTTPAPI/2.0');

        AitanaAccountWS.wsSF_Clientes_List clientesList = new AitanaAccountWS.wsSF_Clientes_List();
        List<AitanaAccountWS.wsSF_Clientes> clientes = new List<AitanaAccountWS.wsSF_Clientes>();
        for (Account account_x : accounts.values()) {
            AitanaAccountWS.wsSF_Clientes cliente = new AitanaAccountWS.wsSF_Clientes();
            cliente.Key = account_x.ERUM_Codigo_cliente_ERP__c;
            cliente.No = account_x.Numero_cliente_ERP__c;
            cliente.Blocked = account_x.ERUM_Estado__c == 'Activo' || account_x.ERUM_Estado__c == 'Nuevo' ? '_blank_' : 'All';
            cliente.Name = account_x.Name;
            cliente.VAT_Registration_No = account_x.ERUM_CIF_Europeo__c;
            cliente.Home_Page = account_x.Website;
            cliente.Phone_No = account_x.Phone;
            cliente.E_Mail = account_x.ERUM_Email__c;
            cliente.Language_Code = account_x.ERUM_Idioma__c;
            cliente.Currency_Code = account_x.CurrencyIsoCode == 'EUR' ?  null : account_x.CurrencyIsoCode;
            cliente.Salesperson_Code = 'IRENE'; // account_x.ERUM_Comercial_asignado__c;
            /*
            cliente.vCCC_No = account_x.ERUM_Numero_de_cuenta__c;
            cliente.vSWIFT_Code = account_x.ERUM_Codigo_SWIFT__c;
            cliente.vIBAN = account_x.IBAN__c;
            */
            cliente.Tipo_de_cliente = '_blank_';
            if (account_x.BillingStreet != null) {
                cliente.Address = account_x.BillingStreet.length() > 50 ? account_x.BillingStreet.substring(0, 50) : account_x.BillingStreet;
                cliente.Address_2 = account_x.BillingStreet.length() > 50 ? account_x.BillingStreet.substring(51, 100) : null;
            }
            if (account_x.BillingPostalCode != null && account_x.BillingCountry != null) {
                cliente.Post_Code = account_x.BillingPostalCode.startsWith(account_x.BillingCountry + '-') ? account_x.BillingPostalCode : account_x.BillingCountry + '-' + account_x.BillingPostalCode;
            }
            cliente.Payment_Terms_Code = account_x.ERUM_Terminos_de_pago__c;
            cliente.Payment_Method_Code = account_x.ERUM_Forma_de_pago__c;
            cliente.Customer_Posting_Group = account_x.Grupo_Contable_Cliente__c;
            cliente.Gen_Bus_Posting_Group = account_x.Grupo_contable_negocio__c;
            cliente.VAT_Bus_Posting_Group = account_x.Grupo_registro_IVA_negocio__c;
            cliente.vNumSuplemento = account_x.Num_Exp_CYC__c;
            DateTime vFechaExpedienteDt = account_x.Fecha_Exp_CYC__c != null ? DateTime.newInstance(account_x.Fecha_Exp_CYC__c.year(), account_x.Fecha_Exp_CYC__c.month(),account_x.Fecha_Exp_CYC__c.day()) : null;
            String vFechaExpedienteStr = vFechaExpedienteDt != null ? vFechaExpedienteDt.format('yyyy-MM-dd') : null;
            cliente.vFechaExpediente = vFechaExpedienteStr;
            System.debug('cliente.vFechaExpediente: ' + cliente.vFechaExpediente);
            cliente.Dias_Asegurado_CYC = String.valueOf(account_x.Dias_Asegurado_CYC__c);
            // cliente.Credit_Limit_LCY = String.valueOf(account_x.Limite_Credito_CYC__c); -> SÓLO EN EL ALTA
            cliente.vClasificacion = account_x.Clasificacion__c != null ? account_x.Clasificacion__c.toUpperCase() : null;
            cliente.vImporteConcedido = String.valueOf(account_x.ERUM_Importe_Concedido__c);
            cliente.vImporteSolicitado = account_x.ERUM_Importe_solicitado__c != null ? account_x.ERUM_Importe_solicitado__c.replace('.', '') : null;
            System.debug('cliente.vImporteConcedido: ' + cliente.vImporteConcedido);
            System.debug('cliente.vImporteSolicitado: ' + cliente.vImporteSolicitado);
            DateTime vFechaVtoDt = account_x.Fecha_Exp_CYC__c != null ? DateTime.newInstance(account_x.Fecha_Exp_CYC__c.year() + 1, account_x.Fecha_Exp_CYC__c.month(),account_x.Fecha_Exp_CYC__c.day()) : null;
            String vFechaVtoStr = vFechaVtoDt != null ? vFechaVtoDt.format('yyyy-MM-dd') : null;
            cliente.vFechaVto = vFechaVtoStr;
            System.debug('cliente.vFechaVto: ' + cliente.vFechaVto);
            clientes.add(cliente);
        }
        clientesList.wsSF_Clientes = clientes;

        /**
         * RECOGEMOS LAS CUENTAS OBTENIDAS DEL TRIGGER Y LAS USAMOS EN LA LLAMADA UPDATE MULTIPLE.
         */

        List<AitanaAccountWS.wsSF_Clientes> wsSF_ClientesResponse = new List<AitanaAccountWS.wsSF_Clientes>();
        try {
            wsSF_ClientesResponse = clientesPort.UpdateMultiple(clientesList).wsSF_Clientes;
        } catch (CalloutException cEx) {
            System.debug('Excepción producida al actualizar cuentas en el ERP: ' + cEx.getMessage());
            GestionErrores.insertGestionErrores(cEx.getMessage(), 'Salesforce', null, accounts.values()[0].Id, null, 'Clientes');
            return;
        }

        /**
         * RECOGEMOS LAS CUENTAS OBTENIDAS EN LA LLAMADA UPDATE MULTIPLE PARA USARLAS MÁS ADELANTE EN LA LLAMADA READ MULTIPLE.
         */

        System.debug(wsSF_ClientesResponse);

        List<AitanaAccountWS.wsSF_Clientes> wsSF_ReadMultipleResponse = new List<AitanaAccountWS.wsSF_Clientes>();
        if (wsSF_ClientesResponse.size() > 0) {
            List<AitanaAccountWS.wsSF_Clientes_Filter> clientesFilter = new List<AitanaAccountWS.wsSF_Clientes_Filter>();
            for (AitanaAccountWS.wsSF_Clientes cliente : wsSF_ClientesResponse) {
                AitanaAccountWS.wsSF_Clientes_Filter clienteFilter = new AitanaAccountWS.wsSF_Clientes_Filter();
                clienteFilter.Field = 'No';
                clienteFilter.Criteria = cliente.No;
                clientesFilter.add(clienteFilter);
            }
            try {
                wsSF_ReadMultipleResponse = clientesPort.ReadMultiple(clientesFilter, null, 100).wsSF_Clientes;
            } catch (CalloutException cEx2) {
                System.debug('Excepción producida al recuperar cuentas del ERP: ' + cEx2.getMessage());
                GestionErrores.insertGestionErrores(cEx2.getMessage(), 'Salesforce', null, accounts.values()[0].Id, null, 'Clientes');
                return;
            }
        }

        /**
         * RECOGEMOS LAS CUENTAS OBTENIDAS EN LA LLAMADA READ MULTIPLE Y ACTUALIZAMOS LOS VALORES EN SALESFORCE. ¡ASÍ TENEMOS LOS CÓDIGOS MÁS RECIENTES!
         */

        System.debug(wsSF_ReadMultipleResponse);

        if (wsSF_ReadMultipleResponse.size() > 0) {
            Map<String, AitanaAccountWS.wsSF_Clientes> updatedClientes = new Map<String, AitanaAccountWS.wsSF_Clientes>();
            for (AitanaAccountWS.wsSF_Clientes cliente : wsSF_ReadMultipleResponse) {
                updatedClientes.put(cliente.VAT_Registration_No, cliente);
            }
            for (Account account : accounts.values()) {
                Account newInstanceOfAccount = new Account(
                    Id = account.Id,
                    ERUM_Codigo_cliente_ERP__c = updatedClientes.get(account.ERUM_CIF_Europeo__c).Key,
                    Numero_cliente_ERP__c = updatedClientes.get(account.ERUM_CIF_Europeo__c).No,
                    ERUM_Activo_ERP__c = true,
                    ERUM_Fecha_Activo_ERP__c = System.today()
                );
                try {
                    TrgController.setDoNotRunTrigger();
                    Database.update(newInstanceOfAccount, true);
                } catch (DmlException dmlEx) {
                    System.debug('Excepción producida al traer de vuelta el id de la cuenta en la actualización: ' + dmlEx.getMessage());
                    GestionErrores.insertGestionErrores(dmlEx.getMessage(), 'Salesforce', null, account.Id, null, 'Clientes');
                    return;
                }
            }
        }

    }
}