force-app/main/default/objects/Account/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asegurado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dias_Asegurado_CYC__c.field-meta.xml
<CustomField>
    <fullName>Dias_Asegurado_CYC__c</fullName>
    <label>Días asegurado CYC</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Activo_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_CIF_Europeo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_CIF_Europeo__c</fullName>
    <label>CIF Europeo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Codigo_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Codigo_cliente_ERP__c</fullName>
    <externalId>true</externalId>
    <label>Código cliente ERP</label>
    <length>225</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Email__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Estado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Estado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Fecha_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Activo_ERP__c</fullName>
    <label>Fecha Activo ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Forma_de_pago__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Forma_de_pago__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Forma_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Idioma__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Importe_Concedido__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Importe_Concedido__c</fullName>
    <label>Importe Concedido</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Importe_solicitado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Importe_solicitado__c</fullName>
    <label>Importe solicitado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3.000</fullName>
            </value>
            <value>
                <fullName>6.000</fullName>
            </value>
            <value>
                <fullName>12.000</fullName>
            </value>
            <value>
                <fullName>30.000</fullName>
            </value>
            <value>
                <fullName>60.000</fullName>
            </value>
            <value>
                <fullName>120.000</fullName>
            </value>
            <value>
                <fullName>500.000</fullName>
            </value>
            <value>
                <fullName>1.000.000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Terminos_de_pago__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Terminos_de_pago__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Términos de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Terminos_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Exp_CYC__c</fullName>
    <label>Fecha Expediente CYC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_Contable_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Grupo_Contable_Cliente__c</fullName>
    <label>Grupo Contable Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_Contable_Cliente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_contable_negocio__c.field-meta.xml
<CustomField>
    <fullName>Grupo_contable_negocio__c</fullName>
    <label>Grupo contable negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_registro_IVA_negocio__c.field-meta.xml
<CustomField>
    <fullName>Grupo_registro_IVA_negocio__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Grupo registro IVA negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_registro_IVA_negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Limite_Credito_CYC__c.field-meta.xml
<CustomField>
    <fullName>Limite_Credito_CYC__c</fullName>
    <label>Límite de crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Num_Exp_CYC__c</fullName>
    <label>Núm. Exped. CYC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>Numero_cliente_ERP__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente ERP</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/ERUM_Direcciones_Envio__c.object-meta.xml
<CustomObject>
    <label>Direcciones Envio</label>
    <nameField>
        <label>Nombre Dirección</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direcciones Envio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Activa_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Activa_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si está marcado indica que el ERP ha confirmado que la Dirección se ha podido crear en su sistema.</description>
    <label>Activa ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Nombre_comercial__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Nombre_comercial__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nombre comercial</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Direcciones Envio</relationshipLabel>
    <relationshipName>Direcciones_Envio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/Numero_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>Numero_cliente_ERP__c</fullName>
    <formula>ERUM_Nombre_comercial__r.Numero_cliente_ERP__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número cliente ERP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ERUM_Estado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nuevo</fullName>
    </customValue>
    <customValue>
        <fullName>En Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Fin de Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Convertido</fullName>
    </customValue>
    <customValue>
        <fullName>Activo</fullName>
    </customValue>
    <customValue>
        <fullName>Inactivo</fullName>
    </customValue>
    <customValue>
        <fullName>Pausado</fullName>
    </customValue>
    <masterLabel>Estado</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ERUM_Terminos_de_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <label>0 DIAS</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 DIAS</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15 DIAS</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30 DIAS</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>35 DIAS</label>
    </customValue>
    <customValue>
        <fullName>45</fullName>
        <label>45 DIAS</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
        <label>50 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>60 DIAS</label>
    </customValue>
    <customValue>
        <fullName>70</fullName>
        <label>70 DIAS</label>
    </customValue>
    <customValue>
        <fullName>75</fullName>
        <label>75 DIAS</label>
    </customValue>
    <customValue>
        <fullName>85</fullName>
        <label>85 DIAS</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>150</fullName>
        <label>150 DIAS</label>
    </customValue>
    <customValue>
        <fullName>180</fullName>
        <label>180 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30-70% ADV</fullName>
        <label>30% in advance 70% against BL copy</label>
    </customValue>
    <customValue>
        <fullName>50-50%</fullName>
        <label>50% Advance / 50% Loaded</label>
    </customValue>
    <customValue>
        <fullName>50% 50%</fullName>
        <label>50%TT in advance / 50%, 30 days TT date invoice</label>
    </customValue>
    <customValue>
        <fullName>100%ADVANC</fullName>
        <label>100% Advance</label>
    </customValue>
    <customValue>
        <fullName>30-60</fullName>
        <label>2PLAZ 60 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60-90</fullName>
        <label>2PLAZ 90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>90-120</fullName>
        <label>2PLAZ 120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30-60-90</fullName>
        <label>3PLAZ 90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60-90-120</fullName>
        <label>3PLAZ 120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>ZARA</fullName>
        <label>Zara</label>
    </customValue>
    <masterLabel>Términos de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Forma_de_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CONF</fullName>
        <label>Confirming</label>
    </customValue>
    <customValue>
        <fullName>DOM</fullName>
        <label>Recibo domiciliado</label>
    </customValue>
    <customValue>
        <fullName>GIR</fullName>
        <label>Giro</label>
    </customValue>
    <customValue>
        <fullName>GRU</fullName>
        <label>Empresas vinculadas grupo</label>
    </customValue>
    <customValue>
        <fullName>PAG</fullName>
        <label>Pagaré</label>
    </customValue>
    <customValue>
        <fullName>PAG-E</fullName>
        <label>Pagaré emitido proveedores</label>
    </customValue>
    <customValue>
        <fullName>RCONF</fullName>
        <label>RECIBIDO CONFIRMING</label>
    </customValue>
    <customValue>
        <fullName>TRF</fullName>
        <label>Transferencia</label>
    </customValue>
    <customValue>
        <fullName>TRFBKINUSD</fullName>
        <label>Transferencia USD</label>
    </customValue>
    <customValue>
        <fullName>TRFBNK</fullName>
        <label>Transferencia Bankinter</label>
    </customValue>
    <masterLabel>Forma de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_Contable_Cliente.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GCGNA</fullName>
        <label>Nac. del Grupo - Grupo Clientes</label>
    </customValue>
    <customValue>
        <fullName>GCGRM</fullName>
        <label>RM del Grupo - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCGUE</fullName>
        <label>UE del Grupo - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCNA</fullName>
        <label>Nacional - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCRM</fullName>
        <label>Resto Mundo - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GCUE</fullName>
        <label>UE - Grupo clientes</label>
    </customValue>
    <customValue>
        <fullName>GDUE</fullName>
        <isActive>false</isActive>
        <label>GDUE</label>
    </customValue>
    <customValue>
        <fullName>GDRM</fullName>
        <isActive>false</isActive>
        <label>GDRM</label>
    </customValue>
    <customValue>
        <fullName>GDNA</fullName>
        <isActive>false</isActive>
        <label>GDNA</label>
    </customValue>
    <customValue>
        <fullName>GCDCUE</fullName>
        <isActive>false</isActive>
        <label>GCDCUE</label>
    </customValue>
    <customValue>
        <fullName>GCDCRM</fullName>
        <isActive>false</isActive>
        <label>GCDCRM</label>
    </customValue>
    <customValue>
        <fullName>GCDCNA</fullName>
        <isActive>false</isActive>
        <label>GCDCNA</label>
    </customValue>
    <masterLabel>Grupo Contable Cliente</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_negocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EXPORT</fullName>
        <label>Otros clientes y proveedores (no UE)</label>
    </customValue>
    <customValue>
        <fullName>NAC</fullName>
        <label>Clientes y proveedores nacionales</label>
    </customValue>
    <customValue>
        <fullName>UE</fullName>
        <label>Clientes y proveedores UE</label>
    </customValue>
    <customValue>
        <fullName>INTERCOMP</fullName>
        <isActive>false</isActive>
        <label>Intercompany</label>
    </customValue>
    <masterLabel>Grupo contable negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Idioma.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ESP</fullName>
        <label>Español</label>
    </customValue>
    <customValue>
        <fullName>ENG</fullName>
        <label>Inglés</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <label>Francés</label>
    </customValue>
    <customValue>
        <fullName>DEU</fullName>
        <label>Alemán</label>
    </customValue>
    <customValue>
        <fullName>PTG</fullName>
        <label>Portugués</label>
    </customValue>
    <customValue>
        <fullName>ITA</fullName>
        <label>Italiano</label>
    </customValue>
    <masterLabel>Idioma</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TrgControllerDireccion.cls
public with sharing class TrgControllerDireccion {

    Map<Id, ERUM_Direcciones_Envio__c> newDirecciones = new Map<Id, ERUM_Direcciones_Envio__c>();

    public TrgControllerDireccion() {

        newDirecciones = (Map<Id, ERUM_Direcciones_Envio__c>) Trigger.newMap;

        Map<Id, Account> accountsToInsert = new Map<Id, Account>();
        Map<Id, ERUM_Direcciones_Envio__c> direccionesToInsert = new Map<Id, ERUM_Direcciones_Envio__c>();
        Map<Id, ERUM_Direcciones_Envio__c> direccionesToUpdate = new Map<Id, ERUM_Direcciones_Envio__c>();

        List<Id> accountIds = new List<Id>();
        for (ERUM_Direcciones_Envio__c newDireccion : newDirecciones.values()) {
            accountIds.add(newDireccion.ERUM_Nombre_comercial__c);
        }

        Map<String, Schema.RecordTypeInfo> recordTypeInfoMap = Schema.SObjectType.Account.getRecordTypeInfosByName();
        List<Account> accounts = new List<Account>();
        accounts = [
            SELECT Id, ERUM_Estado__c, Name, ERUM_CIF_Europeo__c, Website, Phone, ERUM_Email__c, ERUM_Idioma__c, CurrencyIsoCode, IBAN__c, BillingStreet, BillingPostalCode, BillingCountry, ERUM_Terminos_de_pago__c, ERUM_Forma_de_pago__c, Grupo_Contable_Cliente__c, Grupo_contable_negocio__c, Grupo_registro_IVA_negocio__c, Num_Exp_CYC__c, Fecha_Exp_CYC__c, Dias_Asegurado_CYC__c, Limite_Credito_CYC__c, Clasificacion__c, ERUM_Importe_Concedido__c, ERUM_Importe_solicitado__c, ERUM_Codigo_cliente_ERP__c, Numero_cliente_ERP__c, ERUM_Activo_ERP__c, ERUM_Fecha_Activo_ERP__c
            FROM Account 
            WHERE RecordTypeId =: recordTypeInfoMap.get('Cliente').getRecordTypeId() 
            AND Id IN: accountIds
        ];

        Map<Id, Account> accountMap = new Map<Id, Account>();
        for (Account acc : accounts) {
            if (!accountMap.containsKey(acc.Id)) {
                accountMap.put(acc.Id, acc);
            }
        }

        if (Trigger.isAfter && Trigger.isInsert) {
            for (ERUM_Direcciones_Envio__c newDireccion : newDirecciones.values()) {
                
                Account dirAccount = accountMap.get(newDireccion.ERUM_Nombre_comercial__c);
                
                if (dirAccount != null) {
                    
                    if (String.isBlank(dirAccount.Numero_cliente_ERP__c)) {
                        accountsToInsert.put(dirAccount.Id, dirAccount);
                    }
                    direccionesToInsert.put(newDireccion.Id, newDireccion);
                    
                }
            }
        }

        if (Trigger.isAfter && Trigger.isUpdate) {
            for (ERUM_Direcciones_Envio__c newDireccion : newDirecciones.values()) {
                
                Account dirAccount = accountMap.get(newDireccion.ERUM_Nombre_comercial__c);
                
                if (dirAccount != null) {
                    
                    if (String.isBlank(dirAccount.Numero_cliente_ERP__c)) {
                        accountsToInsert.put(dirAccount.Id, dirAccount);
                    }
                    if (newDireccion.ERUM_Activa_ERP__c) {
                        direccionesToUpdate.put(newDireccion.Id, newDireccion);
                    } else {
                        direccionesToInsert.put(newDireccion.Id, newDireccion);
                    }

                }
            }
        }

        if (direccionesToInsert.size() > 0 || direccionesToUpdate.size() > 0) {
            Id jobId1 = System.enqueueJob(new QueueableDireccion(accountsToInsert, direccionesToInsert, direccionesToUpdate));
            System.debug(jobId1);
        }
        
    }

    public class QueueableDireccion implements Queueable, Database.AllowsCallouts {

        private Map<Id, Account> accsToInsert;
        private Map<Id, ERUM_Direcciones_Envio__c> dirsToInsert;
        private Map<Id, ERUM_Direcciones_Envio__c> dirsToUpdate;


        public QueueableDireccion(Map<Id, Account> accsToInsert_x, Map<Id, ERUM_Direcciones_Envio__c> dirsToInsert_x, Map<Id, ERUM_Direcciones_Envio__c> dirsToUpdate_x) {
            this.accsToInsert = accsToInsert_x;
            this.dirsToInsert = dirsToInsert_x;
            this.dirsToUpdate = dirsToUpdate_x;
        }

        public void execute(System.QueueableContext context) {
            if (accsToInsert.size() > 0) {
                WSAccount.insertAccount(JSON.serialize(accsToInsert));
            }
            Id jobId2 = Test.isRunningTest() ? null : System.enqueueJob(new WSQueueableDireccion.QueueableDireccionInsert(dirsToInsert, dirsToUpdate));
            System.debug(jobId2);
        }
    }
}