force-app/main/default/objects/Account/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asegurado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dias_Asegurado_CYC__c.field-meta.xml
<CustomField>
    <fullName>Dias_Asegurado_CYC__c</fullName>
    <label>Días asegurado CYC</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Activo_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_CIF_Europeo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_CIF_Europeo__c</fullName>
    <label>CIF Europeo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Codigo_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Codigo_cliente_ERP__c</fullName>
    <externalId>true</externalId>
    <label>Código cliente ERP</label>
    <length>225</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Email__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Estado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Estado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Fecha_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Activo_ERP__c</fullName>
    <label>Fecha Activo ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Forma_de_pago__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Forma_de_pago__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Forma_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Idioma__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Importe_Concedido__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Importe_Concedido__c</fullName>
    <label>Importe Concedido</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Terminos_de_pago__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Terminos_de_pago__c</fullName>
    <defaultValue>&apos;Sin datos&apos;</defaultValue>
    <label>Términos de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Terminos_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Exp_CYC__c</fullName>
    <label>Fecha Expediente CYC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Limite_Credito_CYC__c.field-meta.xml
<CustomField>
    <fullName>Limite_Credito_CYC__c</fullName>
    <label>Límite de crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Num_Exp_CYC__c</fullName>
    <label>Núm. Exped. CYC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>Numero_cliente_ERP__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente ERP</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/ERUM_Estado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nuevo</fullName>
    </customValue>
    <customValue>
        <fullName>En Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Fin de Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Convertido</fullName>
    </customValue>
    <customValue>
        <fullName>Activo</fullName>
    </customValue>
    <customValue>
        <fullName>Inactivo</fullName>
    </customValue>
    <customValue>
        <fullName>Pausado</fullName>
    </customValue>
    <masterLabel>Estado</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ERUM_Terminos_de_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <label>0 DIAS</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 DIAS</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15 DIAS</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30 DIAS</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>35 DIAS</label>
    </customValue>
    <customValue>
        <fullName>45</fullName>
        <label>45 DIAS</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
        <label>50 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>60 DIAS</label>
    </customValue>
    <customValue>
        <fullName>70</fullName>
        <label>70 DIAS</label>
    </customValue>
    <customValue>
        <fullName>75</fullName>
        <label>75 DIAS</label>
    </customValue>
    <customValue>
        <fullName>85</fullName>
        <label>85 DIAS</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>150</fullName>
        <label>150 DIAS</label>
    </customValue>
    <customValue>
        <fullName>180</fullName>
        <label>180 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30-70% ADV</fullName>
        <label>30% in advance 70% against BL copy</label>
    </customValue>
    <customValue>
        <fullName>50-50%</fullName>
        <label>50% Advance / 50% Loaded</label>
    </customValue>
    <customValue>
        <fullName>50% 50%</fullName>
        <label>50%TT in advance / 50%, 30 days TT date invoice</label>
    </customValue>
    <customValue>
        <fullName>100%ADVANC</fullName>
        <label>100% Advance</label>
    </customValue>
    <customValue>
        <fullName>30-60</fullName>
        <label>2PLAZ 60 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60-90</fullName>
        <label>2PLAZ 90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>90-120</fullName>
        <label>2PLAZ 120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>30-60-90</fullName>
        <label>3PLAZ 90 DIAS</label>
    </customValue>
    <customValue>
        <fullName>60-90-120</fullName>
        <label>3PLAZ 120 DIAS</label>
    </customValue>
    <customValue>
        <fullName>ZARA</fullName>
        <label>Zara</label>
    </customValue>
    <masterLabel>Términos de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Forma_de_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CONF</fullName>
        <label>Confirming</label>
    </customValue>
    <customValue>
        <fullName>DOM</fullName>
        <label>Recibo domiciliado</label>
    </customValue>
    <customValue>
        <fullName>GIR</fullName>
        <label>Giro</label>
    </customValue>
    <customValue>
        <fullName>GRU</fullName>
        <label>Empresas vinculadas grupo</label>
    </customValue>
    <customValue>
        <fullName>PAG</fullName>
        <label>Pagaré</label>
    </customValue>
    <customValue>
        <fullName>PAG-E</fullName>
        <label>Pagaré emitido proveedores</label>
    </customValue>
    <customValue>
        <fullName>RCONF</fullName>
        <label>RECIBIDO CONFIRMING</label>
    </customValue>
    <customValue>
        <fullName>TRF</fullName>
        <label>Transferencia</label>
    </customValue>
    <customValue>
        <fullName>TRFBKINUSD</fullName>
        <label>Transferencia USD</label>
    </customValue>
    <customValue>
        <fullName>TRFBNK</fullName>
        <label>Transferencia Bankinter</label>
    </customValue>
    <masterLabel>Forma de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Idioma.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ESP</fullName>
        <label>Español</label>
    </customValue>
    <customValue>
        <fullName>ENG</fullName>
        <label>Inglés</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <label>Francés</label>
    </customValue>
    <customValue>
        <fullName>DEU</fullName>
        <label>Alemán</label>
    </customValue>
    <customValue>
        <fullName>PTG</fullName>
        <label>Portugués</label>
    </customValue>
    <customValue>
        <fullName>ITA</fullName>
        <label>Italiano</label>
    </customValue>
    <masterLabel>Idioma</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestWSAccount.cls
@isTest
public class TestWSAccount {
    
    public class AccountMock implements WebServiceMock {

        public void doInvoke(
            Object stub,
            Object request,
            Map<String, Object> response,
            String endpoint,
            String soapAction,
            String requestName,
            String responseNS,
            String responseName,
            String responseType
        ) {
            
            AitanaAccountWS.wsSF_Clientes cliente = new AitanaAccountWS.wsSF_Clientes();
            cliente.Key = 'test';
            cliente.No = 'test';
            cliente.Name = 'test';
            cliente.VAT_Registration_No = 'test';
            cliente.Home_Page = 'test';
            cliente.Tipo_de_cliente = 'test';
            cliente.Currency_Code = 'test';
            cliente.Direccion_envio_principal = 'test';
            cliente.Usuario_alta = 'test';
            cliente.Address = 'test';
            cliente.Address_2 = 'test';
            cliente.Post_Code = 'test';
            cliente.Phone_No = 'test';
            cliente.Payment_Terms_Code = 'test';
            cliente.Salesperson_Code = 'test';
            cliente.Payment_Method_Code = 'test';
            cliente.Customer_Posting_Group = 'test';
            cliente.Gen_Bus_Posting_Group = 'test';
            cliente.VAT_Bus_Posting_Group = 'test';
            cliente.Blocked = 'test';
            cliente.E_Mail = 'test';
            cliente.Language_Code = 'test';
            cliente.vCCC_No = 'test';
            cliente.vSWIFT_Code = 'test';
            cliente.vIBAN = 'test';
            cliente.Num_Exped_CYC = 'test';
            cliente.Fecha_Expediente_CYC = 'test';
            cliente.Dias_Asegurado_CYC = 'test';
            cliente.Credit_Limit_LCY = 'test';
            cliente.vClasificacion = 'test';
            cliente.vImporteConcedido = 'test';

            List<AitanaAccountWS.wsSF_Clientes> clientes = new List<AitanaAccountWS.wsSF_Clientes>();
            clientes.add(cliente);

            AitanaAccountWS.wsSF_Clientes_List clientesList = new AitanaAccountWS.wsSF_Clientes_List();
            clientesList.wsSF_Clientes = clientes;

            if (requestName == 'CreateMultiple') {
                AitanaAccountWS.CreateMultiple_Result_element createResult = new AitanaAccountWS.CreateMultiple_Result_element();
                createResult.wsSF_Clientes_List = clientesList;
                response.put('response_x', createResult);
            } else if (requestName == 'UpdateMultiple') {
                AitanaAccountWS.UpdateMultiple_Result_element updateResult = new AitanaAccountWS.UpdateMultiple_Result_element();
                updateResult.wsSF_Clientes_List = clientesList;
                response.put('response_x', updateResult);
            } else if (requestName == 'ReadMultiple') {
                AitanaAccountWS.ReadMultiple_Result_element readResult = new AitanaAccountWS.ReadMultiple_Result_element();
                readResult.ReadMultiple_Result = clientesList;
                response.put('response_x', readResult);
            } else {
                response.put('response_x', null);
            }
            

        }
    }

    public class AccountMockError implements WebServiceMock {

        public void doInvoke(
            Object stub,
            Object request,
            Map<String, Object> response,
            String endpoint,
            String soapAction,
            String requestName,
            String responseNS,
            String responseName,
            String responseType
        ) {
            
            AitanaAccountWS.wsSF_Clientes cliente = new AitanaAccountWS.wsSF_Clientes();
            cliente.Key = 'test';
            cliente.No = 'Este número tiene más de 50 caracteres y debe dar error para que los tests unitarios 5 y 6 lancen una excepción.';
            cliente.Name = 'test';
            cliente.VAT_Registration_No = 'test';
            cliente.Home_Page = 'test';
            cliente.Tipo_de_cliente = 'test';
            cliente.Currency_Code = 'test';
            cliente.Direccion_envio_principal = 'test';
            cliente.Usuario_alta = 'test';
            cliente.Address = 'test';
            cliente.Address_2 = 'test';
            cliente.Post_Code = 'test';
            cliente.Phone_No = 'test';
            cliente.Payment_Terms_Code = 'test';
            cliente.Salesperson_Code = 'test';
            cliente.Payment_Method_Code = 'test';
            cliente.Customer_Posting_Group = 'test';
            cliente.Gen_Bus_Posting_Group = 'test';
            cliente.VAT_Bus_Posting_Group = 'test';
            cliente.Blocked = 'test';
            cliente.E_Mail = 'test';
            cliente.Language_Code = 'test';
            cliente.vCCC_No = 'test';
            cliente.vSWIFT_Code = 'test';
            cliente.vIBAN = 'test';
            cliente.Num_Exped_CYC = 'test';
            cliente.Fecha_Expediente_CYC = 'test';
            cliente.Dias_Asegurado_CYC = 'test';
            cliente.Credit_Limit_LCY = 'test';
            cliente.vClasificacion = 'test';
            cliente.vImporteConcedido = 'test';

            List<AitanaAccountWS.wsSF_Clientes> clientes = new List<AitanaAccountWS.wsSF_Clientes>();
            clientes.add(cliente);

            AitanaAccountWS.wsSF_Clientes_List clientesList = new AitanaAccountWS.wsSF_Clientes_List();
            clientesList.wsSF_Clientes = clientes;

            if (requestName == 'CreateMultiple') {
                AitanaAccountWS.CreateMultiple_Result_element createResult = new AitanaAccountWS.CreateMultiple_Result_element();
                createResult.wsSF_Clientes_List = clientesList;
                response.put('response_x', createResult);
            } else if (requestName == 'UpdateMultiple') {
                AitanaAccountWS.UpdateMultiple_Result_element updateResult = new AitanaAccountWS.UpdateMultiple_Result_element();
                updateResult.wsSF_Clientes_List = clientesList;
                response.put('response_x', updateResult);
            } else if (requestName == 'ReadMultiple') {
                AitanaAccountWS.ReadMultiple_Result_element readResult = new AitanaAccountWS.ReadMultiple_Result_element();
                readResult.ReadMultiple_Result = clientesList;
                response.put('response_x', readResult);
            } else {
                response.put('response_x', null);
            }
            

        }
    }

    @TestSetup
    static void makeData(){

        TrgController.setDoNotRunTrigger();
        
        Id clientePotencialRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Potencial').getRecordTypeId();
        Id clienteRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente').getRecordTypeId();

        Account account_x = new Account(
            Name = 'cuentaTestx testCuentax',
            Phone = '12345678',
            RecordTypeId = clientePotencialRecordType,
            ERUM_CIF_Europeo__c = 'test',
            ERUM_Idioma__c = 'ESP',
            ERUM_Estado__c = 'Nuevo',
            CurrencyIsoCode = 'EUR',
            BillingStreet = 'Calle Fernán Caballero, número 11, piso 2, puerta A Izquierda',
            BillingPostalCode = '11003',
            BillingCountry = 'ES',
            Num_Exp_CYC__c = '1',
            Fecha_Exp_CYC__c = System.today(),
            Dias_Asegurado_CYC__c = 365,
            Limite_Credito_CYC__c = 125000,
            ERUM_Importe_Concedido__c = 25000,
            ERUM_Activo_ERP__c = false,
            ERUM_Codigo_cliente_ERP__c = null,
            Numero_cliente_ERP__c = null,
            ERUM_Fecha_Activo_ERP__c = null,
            Clasificacion__c = null
        );

        insert account_x;

        Account account_y = new Account(
            Name = 'testCuentay cuentaTesty',
            Phone = '12345679',
            RecordTypeId = clienteRecordType,
            ERUM_CIF_Europeo__c = 'test',
            ERUM_Idioma__c = 'ESP',
            ERUM_Estado__c = 'Activo',
            CurrencyIsoCode = 'EUR',
            BillingStreet = 'Calle Cánovas del Castillo, número 12, piso 3, puerta B Derecha',
            BillingPostalCode = '11003',
            BillingCountry = 'ES',
            Num_Exp_CYC__c = '1',
            Fecha_Exp_CYC__c = System.today(),
            Dias_Asegurado_CYC__c = 365,
            Limite_Credito_CYC__c = 125000,
            ERUM_Importe_Concedido__c = 25000,
            ERUM_Activo_ERP__c = true,
            ERUM_Codigo_cliente_ERP__c = 'test0',
            Numero_cliente_ERP__c = 'test',
            ERUM_Fecha_Activo_ERP__c = System.today(),
            Clasificacion__c = 'Asegurado'
        );

        insert account_y;
    }

    /**
     * TRIGGER ACCOUNT ON UPDATE
     */

    @isTest(SeeAllData=false)
    public static void testWSAccount_1() {
        Account test1 = [
            SELECT Id, RecordTypeId, ERUM_Estado__c, Name, ERUM_CIF_Europeo__c, Website, Phone, ERUM_Email__c, ERUM_Idioma__c, CurrencyIsoCode, IBAN__c, BillingStreet, BillingPostalCode, BillingCountry, ERUM_Terminos_de_pago__c, ERUM_Forma_de_pago__c, Num_Exp_CYC__c, Fecha_Exp_CYC__c, Dias_Asegurado_CYC__c, Limite_Credito_CYC__c, ERUM_Importe_Concedido__c 
            FROM Account 
            WHERE Name =: 'cuentaTestx testCuentax'
            LIMIT 1
        ];

        Test.setMock(WebServiceMock.class, new AccountMock());
        Test.startTest();
        test1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente').getRecordTypeId();
        Database.update(test1, true);
        Test.stopTest();
    }

    /**
     * TRIGGER ACCOUNT ON CREATE
     */

    @isTest(SeeAllData=false)
    public static void testWSAccount_2() {
        Account test2 = new Account(
            Name = 'test2 cuenta2',
            Phone = '12345677',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente').getRecordTypeId(),
            ERUM_CIF_Europeo__c = 'test',
            ERUM_Idioma__c = 'ESP',
            ERUM_Estado__c = 'Activo',
            CurrencyIsoCode = 'EUR',
            BillingStreet = 'Calle Enrique de las Marinas, número 13, piso 4, puerta C Derecha',
            BillingPostalCode = '11003',
            BillingCountry = 'ES',
            Num_Exp_CYC__c = '1',
            Fecha_Exp_CYC__c = System.today(),
            Dias_Asegurado_CYC__c = 365,
            Limite_Credito_CYC__c = 125000,
            ERUM_Importe_Concedido__c = 25000,
            ERUM_Activo_ERP__c = false,
            ERUM_Codigo_cliente_ERP__c = null,
            Numero_cliente_ERP__c = null,
            ERUM_Fecha_Activo_ERP__c = null,
            Clasificacion__c = null
        );
        Test.setMock(WebServiceMock.class, new AccountMock());
        Test.startTest();
        Database.insert(test2, true);
        Test.stopTest();
    }

    /**
     * BOTÓN PARA INSERTAR CLIENTE INACTIVO
     */

    @isTest(SeeAllData=false)
    public static void testWSAccount_3() {
        Account test3 = [SELECT Id, Phone, ERUM_CIF_Europeo__c, ERUM_Activo_ERP__c, ERUM_Codigo_cliente_ERP__c FROM Account WHERE Name =: 'cuentaTestx testCuentax' LIMIT 1];
        PageReference pRef = Page.ButtonWSAccountPage;
        Test.setMock(WebServiceMock.class, new AccountMock());
        Test.setCurrentPage(pRef);
        Test.startTest();
        ApexPages.StandardController sCtrl = new ApexPages.StandardController(test3);
        ButtonWSAccountController ctrl = new ButtonWSAccountController(sCtrl);
        ctrl.upsertAccount();
        Test.stopTest();
    }

    /**
     * BOTÓN PARA EDITAR CLIENTE ACTIVO
     */

    @isTest(SeeAllData=false)
    public static void testWSAccount_4() {
        Account test4 = [SELECT Id, Phone, ERUM_CIF_Europeo__c, ERUM_Activo_ERP__c, ERUM_Codigo_cliente_ERP__c FROM Account WHERE Name =: 'testCuentay cuentaTesty' LIMIT 1];
        PageReference pRef = Page.ButtonWSAccountPage;
        Test.setMock(WebServiceMock.class, new AccountMock());
        Test.setCurrentPage(pRef);
        Test.startTest();
        ApexPages.StandardController sCtrl = new ApexPages.StandardController(test4);
        ButtonWSAccountController ctrl = new ButtonWSAccountController(sCtrl);
        ctrl.upsertAccount();
        Test.stopTest();
    }

    
    /**
     * TRIGGER ACCOUNT ON UPDATE FAILURE
     */

    @isTest(SeeAllData=false)
    public static void testWSAccount_5() {
        Account test5 = [
            SELECT Id, RecordTypeId, ERUM_Estado__c, Name, ERUM_CIF_Europeo__c, Website, Phone, ERUM_Email__c, ERUM_Idioma__c, CurrencyIsoCode, IBAN__c, BillingStreet, BillingPostalCode, BillingCountry, ERUM_Terminos_de_pago__c, ERUM_Forma_de_pago__c, Num_Exp_CYC__c, Fecha_Exp_CYC__c, Dias_Asegurado_CYC__c, Limite_Credito_CYC__c, ERUM_Importe_Concedido__c 
            FROM Account 
            WHERE Name =: 'cuentaTestx testCuentax'
            LIMIT 1
        ];

        Test.setMock(WebServiceMock.class, new AccountMockError());
        Test.startTest();
        test5.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente').getRecordTypeId();
        Database.update(test5, true);
        Test.stopTest();
    }
 
    /**
     * BOTÓN PARA EDITAR CLIENTE ACTIVO FAILURE
     */
 
    @isTest(SeeAllData=false)
    public static void testWSAccount_6() {
        Account test6 = [SELECT Id, Phone, ERUM_CIF_Europeo__c, ERUM_Activo_ERP__c, ERUM_Codigo_cliente_ERP__c FROM Account WHERE Name =: 'testCuentay cuentaTesty' LIMIT 1];
        PageReference pRef = Page.ButtonWSAccountPage;
        Test.setMock(WebServiceMock.class, new AccountMockError());
        Test.setCurrentPage(pRef);
        Test.startTest();
        ApexPages.StandardController sCtrl = new ApexPages.StandardController(test6);
        ButtonWSAccountController ctrl = new ButtonWSAccountController(sCtrl);
        ctrl.upsertAccount();
        Test.stopTest();
    }

}