force-app/main/default/objects/Account/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asegurado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dias_Asegurado_CYC__c.field-meta.xml
<CustomField>
    <fullName>Dias_Asegurado_CYC__c</fullName>
    <label>Días asegurado CYC</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_CIF_Europeo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_CIF_Europeo__c</fullName>
    <label>CIF Europeo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Estado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Estado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Exp_CYC__c</fullName>
    <label>Fecha Expediente CYC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Limite_Credito_CYC__c.field-meta.xml
<CustomField>
    <fullName>Limite_Credito_CYC__c</fullName>
    <label>Límite de crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Num_Exp_CYC__c</fullName>
    <label>Núm. Exped. CYC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ERUM_Estado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nuevo</fullName>
    </customValue>
    <customValue>
        <fullName>En Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Fin de Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Convertido</fullName>
    </customValue>
    <customValue>
        <fullName>Activo</fullName>
    </customValue>
    <customValue>
        <fullName>Inactivo</fullName>
    </customValue>
    <customValue>
        <fullName>Pausado</fullName>
    </customValue>
    <masterLabel>Estado</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GestionRiesgosController.cls
public class GestionRiesgosController {
    
    public Account potencial;
    public String cif {get;set;}
    public String numeroExp {get;set;}
    public Date fechaExp {get;set;}
    public Decimal diasAsegurado {get;set;}
    public String limiteCredito {get;set;}
    public String clasificacion {get;set;}
    public String errorDetail {get;set;}
    public Boolean errorIsNotNull {get; set;}
    public String successDetail {get;set;}
    public Boolean successIsNotNull {get; set;}
    public List<SelectOption> clasificacionList {
        get {
            List<SelectOption> options = new List<SelectOption>();
            Schema.DescribeFieldResult fieldResult = Account.Clasificacion__c.getDescribe();
            List<Schema.PicklistEntry> entries = fieldResult.getPicklistValues();
            for (Schema.PicklistEntry entry : entries) {
                options.add(new SelectOption(entry.getValue(), entry.getLabel()));
            }
            return options;
        }
    }

    public GestionRiesgosController() {
        errorIsNotNull = false;
        successIsNotNull = false;
        cif = ApexPages.currentpage().getparameters().get('cif');
    }

    public void updateClientePotencial() {
        potencial = [
            SELECT Id, ERUM_CIF_Europeo__c, Num_Exp_CYC__c, Fecha_Exp_CYC__c, Dias_Asegurado_CYC__c, Limite_Credito_CYC__c, Clasificacion__c, ERUM_Estado__c
            FROM Account 
            WHERE ERUM_CIF_Europeo__c =: cif
            AND RecordType.Name = 'Cliente Potencial'
            LIMIT 1
        ];
        System.debug(potencial.ERUM_CIF_Europeo__c);
        potencial.Num_Exp_CYC__c = numeroExp;
        potencial.Fecha_Exp_CYC__c = fechaExp;
        potencial.Dias_Asegurado_CYC__c = diasAsegurado;
        potencial.Limite_Credito_CYC__c = Decimal.valueOf(limiteCredito);
        potencial.Clasificacion__c = clasificacion;
        potencial.ERUM_Estado__c = 'Fin de Análisis Riesgo';
        System.debug(potencial);
        try {
            errorIsNotNull = false;
            TrgController.setDoNotRunTrigger();
            Database.update(potencial, true);
            successIsNotNull = true;
            successDetail = '¡Envío completado!';
        } catch (DmlException dmlEx1) {
            errorIsNotNull = true;
            successIsNotNull = false;
            System.debug(dmlEx1);
            errorDetail = dmlEx1.getMessage();
        }
    }
}