force-app/main/default/objects/Account/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asegurado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dias_Asegurado_CYC__c.field-meta.xml
<CustomField>
    <fullName>Dias_Asegurado_CYC__c</fullName>
    <label>Días asegurado CYC</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Activo_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_CIF_Europeo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_CIF_Europeo__c</fullName>
    <label>CIF Europeo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Codigo_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Codigo_cliente_ERP__c</fullName>
    <externalId>true</externalId>
    <label>Código cliente ERP</label>
    <length>225</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Estado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERUM_Estado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Fecha_Activo_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Activo_ERP__c</fullName>
    <label>Fecha Activo ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Idioma__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Importe_Concedido__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Importe_Concedido__c</fullName>
    <label>Importe Concedido</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Exp_CYC__c</fullName>
    <label>Fecha Expediente CYC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Limite_Credito_CYC__c.field-meta.xml
<CustomField>
    <fullName>Limite_Credito_CYC__c</fullName>
    <label>Límite de crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Num_Exp_CYC__c.field-meta.xml
<CustomField>
    <fullName>Num_Exp_CYC__c</fullName>
    <label>Núm. Exped. CYC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_cliente_ERP__c.field-meta.xml
<CustomField>
    <fullName>Numero_cliente_ERP__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente ERP</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/ERUM_Estado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nuevo</fullName>
    </customValue>
    <customValue>
        <fullName>En Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Fin de Análisis Riesgo</fullName>
    </customValue>
    <customValue>
        <fullName>Desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Convertido</fullName>
    </customValue>
    <customValue>
        <fullName>Activo</fullName>
    </customValue>
    <customValue>
        <fullName>Inactivo</fullName>
    </customValue>
    <customValue>
        <fullName>Pausado</fullName>
    </customValue>
    <masterLabel>Estado</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Idioma.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ESP</fullName>
        <label>Español</label>
    </customValue>
    <customValue>
        <fullName>ENG</fullName>
        <label>Inglés</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <label>Francés</label>
    </customValue>
    <customValue>
        <fullName>DEU</fullName>
        <label>Alemán</label>
    </customValue>
    <customValue>
        <fullName>PTG</fullName>
        <label>Portugués</label>
    </customValue>
    <customValue>
        <fullName>ITA</fullName>
        <label>Italiano</label>
    </customValue>
    <masterLabel>Idioma</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestGestionRiesgosController.cls
@isTest
public class TestGestionRiesgosController {
    
    @TestSetup
    static void makeData(){

        TrgController.setDoNotRunTrigger();

        Id clientePotencialRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Potencial').getRecordTypeId();

        Account account_x = new Account(
            Name = 'cuentaTestx testCuentax',
            Phone = '12345678',
            RecordTypeId = clientePotencialRecordType,
            ERUM_CIF_Europeo__c = 'test',
            ERUM_Idioma__c = 'ESP',
            ERUM_Estado__c = 'Nuevo',
            CurrencyIsoCode = 'EUR',
            BillingStreet = 'Calle Fernán Caballero, número 11, piso 2, puerta A Izquierda',
            BillingPostalCode = '11003',
            BillingCountry = 'ES',
            Num_Exp_CYC__c = null,
            Fecha_Exp_CYC__c = null,
            Dias_Asegurado_CYC__c = null,
            Limite_Credito_CYC__c = null,
            ERUM_Importe_Concedido__c = null,
            ERUM_Activo_ERP__c = false,
            ERUM_Codigo_cliente_ERP__c = null,
            Numero_cliente_ERP__c = null,
            ERUM_Fecha_Activo_ERP__c = null,
            Clasificacion__c = null
        );

        insert account_x;
        
    }

    @isTest(SeeAllData=false)
    public static void testGestion_1() {
        PageReference pRef = Page.GestionRiesgosPage;
        Test.setCurrentPage(pRef);
        Account account_x = [SELECT Id, Phone, ERUM_CIF_Europeo__c, Num_Exp_CYC__c, Fecha_Exp_CYC__c, Dias_Asegurado_CYC__c, Limite_Credito_CYC__c, Clasificacion__c, ERUM_Estado__c FROM Account WHERE ERUM_CIF_Europeo__c =: 'test' LIMIT 1];
        ApexPages.currentPage().getParameters().put('cif', account_x.ERUM_CIF_Europeo__c);
        GestionRiesgosController ctrl = new GestionRiesgosController();
        ctrl.numeroExp = 'test';
        ctrl.fechaExp = System.today();
        ctrl.diasAsegurado = 365;
        ctrl.limiteCredito = '100000';
        ctrl.clasificacion = 'Asegurado';
        ctrl.updateClientePotencial();

    }

    @isTest(SeeAllData=false)
    public static void testGestion_2() {
        PageReference pRef = Page.GestionRiesgosPage;
        Test.setCurrentPage(pRef);
        Account account_x = [SELECT Id, Phone, ERUM_CIF_Europeo__c, Num_Exp_CYC__c, Fecha_Exp_CYC__c, Dias_Asegurado_CYC__c, Limite_Credito_CYC__c, Clasificacion__c, ERUM_Estado__c FROM Account WHERE ERUM_CIF_Europeo__c =: 'test' LIMIT 1];
        ApexPages.currentPage().getParameters().put('cif', account_x.ERUM_CIF_Europeo__c);
        GestionRiesgosController ctrl = new GestionRiesgosController();
        ctrl.numeroExp = 'test';
        ctrl.fechaExp = System.today();
        ctrl.diasAsegurado = 365;
        ctrl.limiteCredito = '100000';
        ctrl.clasificacion = 'esto va a fallar';
        ctrl.updateClientePotencial();

    }
}