force-app/main/default/objects/Account/fields/ERUM_CIF_Europeo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_CIF_Europeo__c</fullName>
    <label>CIF Europeo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERUM_Idioma__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/ERUM_Direcciones_Envio__c.object-meta.xml
<CustomObject>
    <label>Direcciones Envio</label>
    <nameField>
        <label>Nombre Dirección</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direcciones Envio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ERUM_Direcciones_Envio__c/fields/ERUM_Enviada_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Enviada_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si está marcado indica que Salesforce ha enviado los Datos de Dirección al ERP.</description>
    <label>Enviada ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ERUM_Idioma__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Idioma__c</fullName>
    <formula>TEXT(Account.ERUM_Idioma__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Idioma</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Pedido.recordType-meta.xml
<RecordType>
    <fullName>Pedido</fullName>
    <active>true</active>
    <businessProcess>Pedido</businessProcess>
    <label>Pedido</label>
</RecordType>

force-app/main/default/objects/Pricebook2/fields/ERUM_Fecha_Inicio__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Inicio__c</fullName>
    <label>Fecha Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/ERUM_Moneda__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Moneda__c</fullName>
    <label>Moneda</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/ERUM_PB_Id_External__c.field-meta.xml
<CustomField>
    <fullName>ERUM_PB_Id_External__c</fullName>
    <externalId>true</externalId>
    <label>PB Id External</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/C_d_Unidad_de_medida__c.field-meta.xml
<CustomField>
    <fullName>C_d_Unidad_de_medida__c</fullName>
    <label>Cód.Unidad medida</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAJA</fullName>
            </value>
            <value>
                <fullName>CAPA</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>PALLET</fullName>
            </value>
            <value>
                <fullName>PCS.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Codigo_de_ventas__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Codigo_de_ventas__c</fullName>
    <label>Código de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Fecha_Final__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Final__c</fullName>
    <label>Fecha Final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Fecha_Inicial__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Fecha_Inicial__c</fullName>
    <label>Fecha Inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Incluir_coste_contenedor__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Incluir_coste_contenedor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incluir coste contenedor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Nombre_codigo_de_ventas__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Nombre_codigo_de_ventas__c</fullName>
    <label>Nombre código de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ERUM_Tipo_de_venta__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_de_venta__c</fullName>
    <label>Tipo de venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Grupo precio cliente</fullName>
            </value>
            <value>
                <fullName>Todos los clientes</fullName>
            </value>
            <value>
                <fullName>Campaña</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Alto_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Alto_embalaje__c</fullName>
    <label>Alto embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Ancho_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Ancho_embalaje__c</fullName>
    <label>Ancho embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Ancho_pala__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Ancho_pala__c</fullName>
    <label>Ancho pala</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Bloqueado__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Bloqueado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bloqueado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cantidad_por_palet__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cantidad_por_palet__c</fullName>
    <label>Cantidad por palet</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cod_categoria_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cod_categoria_producto__c</fullName>
    <label>Cód.categoría producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cod_categoria_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Cod_grupo_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Cod_grupo_producto__c</fullName>
    <label>Cód. grupo producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cod_grupo_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Enviada_ERP__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Enviada_ERP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviada ERP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_External_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ERUM_External_ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>Código Producto BC</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_contable_inventario__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_contable_inventario__c</fullName>
    <label>Grupo contable inventario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_inventario</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_contable_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_contable_producto__c</fullName>
    <label>Grupo contable producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_contable_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_prod_Servicio__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_prod_Servicio__c</fullName>
    <label>Grupo prod. Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_prod_Servicio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Grupo_registro_IVA_prod__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Grupo_registro_IVA_prod__c</fullName>
    <label>Grupo registro IVA prod.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_registro_IVA_prod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Largo_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Largo_embalaje__c</fullName>
    <label>Largo embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Material_producto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Material_producto__c</fullName>
    <label>Material producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_producto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Media_percha__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Media_percha__c</fullName>
    <label>Media percha</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Nivel_tecnoligico__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Nivel_tecnoligico__c</fullName>
    <label>Nivel tecnológico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procede</fullName>
            </value>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_bruto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_bruto__c</fullName>
    <label>Peso bruto</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_bruto_cantidad_embalada__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_bruto_cantidad_embalada__c</fullName>
    <label>Peso bruto cantidad embalada</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_embalaje__c</fullName>
    <label>Peso embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_neto__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_neto__c</fullName>
    <label>Peso neto</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Peso_neto_cantidad_embalada__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Peso_neto_cantidad_embalada__c</fullName>
    <label>Peso neto cantidad embalada</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Stock_disponible__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Stock_disponible__c</fullName>
    <inlineHelpText>Recuerde actualizar la página al consultar el Stock, tras 30 segundos, pulsando: &quot;ctrl&quot; + &quot;F5&quot;.</inlineHelpText>
    <label>Stock disponible</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventario</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_de_materia_prima__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_de_materia_prima__c</fullName>
    <label>Tipo de materia prima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procede</fullName>
            </value>
            <value>
                <fullName>Virgen</fullName>
            </value>
            <value>
                <fullName>Reciclado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_de_material__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_de_material__c</fullName>
    <label>Tipo de material</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Tipo_palet__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Tipo_palet__c</fullName>
    <label>Tipo palet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Europeo</fullName>
            </value>
            <value>
                <fullName>Americano</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Unidad_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Unidad_embalaje__c</fullName>
    <label>Unidad embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Volumen__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Volumen__c</fullName>
    <label>Volumen</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ERUM_Volumen_embalaje__c.field-meta.xml
<CustomField>
    <fullName>ERUM_Volumen_embalaje__c</fullName>
    <label>Volumen embalaje</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_envio_ERP__c.field-meta.xml
<CustomField>
    <fullName>Fecha_envio_ERP__c</fullName>
    <label>Fecha envío ERP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Cod_categoria_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALMACEN</fullName>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
        <label>COMPLEMENTOS MADERA</label>
    </customValue>
    <customValue>
        <fullName>CP</fullName>
        <label>COMPLEMENTOS PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>MLD02549</fullName>
        <label>CRF06 30</label>
    </customValue>
    <customValue>
        <fullName>MPM</fullName>
        <label>MATERIA PRIMA MADERA</label>
    </customValue>
    <customValue>
        <fullName>MPP</fullName>
        <label>MATERIA PRIMA PLÁSTICOMATERIA PRIMA PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>PIM</fullName>
        <label>PRODUCTO INTERMEDIO MADERA</label>
    </customValue>
    <customValue>
        <fullName>PIP</fullName>
        <label>PRODUCTO INTERMEDIO PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>PTM</fullName>
        <label>PRODUCTO TERMINADO MADERA</label>
    </customValue>
    <customValue>
        <fullName>PTP</fullName>
        <label>PRODUCTO TERMINADO PLÁSTICO</label>
    </customValue>
    <customValue>
        <fullName>SIN</fullName>
        <label>SIN CLASIFICACION</label>
    </customValue>
    <masterLabel>Cód. categoría producto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_inventario.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ENVASES</fullName>
        <label>Envases y embalajes</label>
    </customValue>
    <customValue>
        <fullName>MAT. PRIMA</fullName>
        <label>Materias primas</label>
    </customValue>
    <customValue>
        <fullName>MERCADERIA</fullName>
        <label>Mercaderías</label>
    </customValue>
    <customValue>
        <fullName>OTROS APRO</fullName>
        <label>Otros aprovisionamientos</label>
    </customValue>
    <customValue>
        <fullName>SERVICIOS</fullName>
        <label>Servicios</label>
    </customValue>
    <customValue>
        <fullName>TERMINADO</fullName>
        <label>Productos terminados</label>
    </customValue>
    <masterLabel>Grupo contable inventario</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_contable_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ARANC CV</fullName>
        <label>Aranceles compra-venta</label>
    </customValue>
    <customValue>
        <fullName>ARANC FAB</fullName>
        <label>Aranceles fabricación</label>
    </customValue>
    <customValue>
        <fullName>GABV</fullName>
        <label>Basura, varios</label>
    </customValue>
    <customValue>
        <fullName>GAEN</fullName>
        <label>Envases</label>
    </customValue>
    <customValue>
        <fullName>GAENA</fullName>
        <label>Envases de automoción</label>
    </customValue>
    <customValue>
        <fullName>GAMEA</fullName>
        <label>Automoción</label>
    </customValue>
    <customValue>
        <fullName>GAMEC</fullName>
        <label>Mercadería compra-venta</label>
    </customValue>
    <customValue>
        <fullName>GAMEF</fullName>
        <label>Mercadería fabricación</label>
    </customValue>
    <customValue>
        <fullName>GAMEI</fullName>
        <label>Mercadería intermediación internacional</label>
    </customValue>
    <customValue>
        <fullName>GAMP</fullName>
        <label>Materia prima</label>
    </customValue>
    <customValue>
        <fullName>GAOA</fullName>
        <label>Otros Aprovisionamientos</label>
    </customValue>
    <customValue>
        <fullName>GAPO</fullName>
        <label>Porte de ventas</label>
    </customValue>
    <customValue>
        <fullName>GAPP</fullName>
        <label>Porte sobre compras</label>
    </customValue>
    <customValue>
        <fullName>VARIOS</fullName>
        <label>Otros diversos, trabajos</label>
    </customValue>
    <customValue>
        <fullName>GAENC</fullName>
        <label>Envases compra-venta</label>
    </customValue>
    <customValue>
        <fullName>TRUEN</fullName>
    </customValue>
    <customValue>
        <fullName>GAMU</fullName>
        <label>Productos de muestra</label>
    </customValue>
    <customValue>
        <fullName>IMP. PLA.</fullName>
    </customValue>
    <customValue>
        <fullName>ARANC INT</fullName>
    </customValue>
    <masterLabel>Grupo contable producto</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_prod_Servicio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GR1</fullName>
    </customValue>
    <masterLabel>Grupo prod. Servicio</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_registro_IVA_prod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EXENTO</fullName>
        <label>Varios IVA Exento</label>
    </customValue>
    <customValue>
        <fullName>IVA04</fullName>
        <label>Varios con IVA 4% supereducido</label>
    </customValue>
    <customValue>
        <fullName>IVA10</fullName>
        <label>Varios con IVA 10% reducido</label>
    </customValue>
    <customValue>
        <fullName>IVA21</fullName>
        <label>Varios con IVA 21%</label>
    </customValue>
    <customValue>
        <fullName>IVABI21</fullName>
        <label>Bienes de inversión 21%</label>
    </customValue>
    <customValue>
        <fullName>IVAS21</fullName>
        <label>Varios servicios con IVA 21%</label>
    </customValue>
    <customValue>
        <fullName>IVA-TI-21</fullName>
        <label>Varios con IVA 21% importación</label>
    </customValue>
    <customValue>
        <fullName>NO SUJETO</fullName>
        <label>Varios IVA NO SUJETO</label>
    </customValue>
    <masterLabel>Grupo registro IVA prod.</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Idioma.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ESP</fullName>
        <label>Español</label>
    </customValue>
    <customValue>
        <fullName>ENG</fullName>
        <label>Inglés</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <label>Francés</label>
    </customValue>
    <customValue>
        <fullName>DEU</fullName>
        <label>Alemán</label>
    </customValue>
    <customValue>
        <fullName>PTG</fullName>
        <label>Portugués</label>
    </customValue>
    <customValue>
        <fullName>ITA</fullName>
        <label>Italiano</label>
    </customValue>
    <masterLabel>Idioma</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Material_producto.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PP</fullName>
        <label>POLIPROPILENO</label>
    </customValue>
    <customValue>
        <fullName>PS</fullName>
        <label>POLIESTIRENO</label>
    </customValue>
    <customValue>
        <fullName>RPP</fullName>
        <label>PP RECICLADO</label>
    </customValue>
    <customValue>
        <fullName>RPS</fullName>
        <label>PS RECICLADO</label>
    </customValue>
    <masterLabel>Material producto</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestWSOpportunity.cls
@isTest
public class TestWSOpportunity {
    
    public class OppMock implements WebServiceMock {

        public void doInvoke(
            Object stub,
            Object request,
            Map<String, Object> response,
            String endpoint,
            String soapAction,
            String requestName,
            String responseNS,
            String responseName,
            String responseType
        ) {
            AitanaOrderWS.wsSF_Pedidos pedido = new AitanaOrderWS.wsSF_Pedidos();
            pedido.Key = 'test';
            pedido.No = 'test';
            pedido.Bill_to_Name = 'test';
            pedido.Order_Date = System.today();
            pedido.Language_Code = 'test';
            pedido.Currency_Code = 'test';
            pedido.Ship_to_Code = 'test';
            pedido.Ship_to_Address = 'test';
            pedido.Your_Reference = 'test';
            pedido.Shipping_Agent_Code = 'test';
            pedido.Payment_Terms_Code = 'test';
            pedido.Shipment_Method_Code = 'test';
            pedido.Payment_Method_Code = 'test';
            pedido.Invoice_Discount_Calculation = 'test';
            pedido.Ship_to_Post_Code = 'test';
            pedido.Ship_to_City = 'test';
            pedido.Ship_to_Country_Region_Code = 'test';
            pedido.Ship_to_Name = 'test';
            pedido.External_Document_No = 'test';
            pedido.Prepayment_Percent = 1.0;
            pedido.Payment_Discount_Percent = 1.0;
            pedido.Document_Type = 'test';
            pedido.No_Series = 'test';
            pedido.Sell_to_Customer_No = 'test';

            AitanaOrderLineWS.wsSF_LinPedido linea = new AitanaOrderLineWS.wsSF_LinPedido();
            linea.Key = 'test';
            linea.Document_No = 'test';
            linea.Line_No = 10000;
            linea.Sell_to_Customer_No = 'test';
            linea.Tariff_No = 'test';
            linea.Line_Discount_Percent = 1.0;
            linea.Shipment_Date = System.today();
            linea.Unit_of_Measure_Code = 'test';
            linea.Description = 'test';
            linea.Description_2 = 'test';
            linea.Unit_Price = 1.0;
            linea.Quantity = 1.0;
            linea.Qty_to_Ship = 1.0;
            linea.Document_Type = 'test';
            linea.No = 'no';

            List<AitanaOrderWS.wsSF_Pedidos> pedidos = new List<AitanaOrderWS.wsSF_Pedidos>();
            List<AitanaOrderLineWS.wsSF_LinPedido> lineas = new List<AitanaOrderLineWS.wsSF_LinPedido>();

            pedidos.add(pedido);
            lineas.add(linea);

            AitanaOrderWS.wsSF_Pedidos_List pedidosList = new AitanaOrderWS.wsSF_Pedidos_List();
            AitanaOrderLineWS.wsSF_LinPedido_List lineasList = new AitanaOrderLineWS.wsSF_LinPedido_List();

            pedidosList.wsSF_Pedidos = pedidos;
            lineasList.wsSF_LinPedido = lineas;

            if (soapAction.contains('wssf_pedidos')) {
                if (requestName == 'CreateMultiple') {
                    AitanaOrderWS.CreateMultiple_Result_element createResultPedidos = new AitanaOrderWS.CreateMultiple_Result_element();
                    createResultPedidos.wsSF_Pedidos_List = pedidosList;
                    response.put('response_x', createResultPedidos);
                } else if (requestName == 'UpdateMultiple') {
                    AitanaOrderWS.UpdateMultiple_Result_element updateResultPedidos = new AitanaOrderWS.UpdateMultiple_Result_element();
                    updateResultPedidos.wsSF_Pedidos_List = pedidosList;
                    response.put('response_x', updateResultPedidos);
                } else if (requestName == 'ReadMultiple') {
                    AitanaOrderWS.ReadMultiple_Result_element readResultPedidos = new AitanaOrderWS.ReadMultiple_Result_element();
                    readResultPedidos.ReadMultiple_Result = pedidosList;
                    response.put('response_x', readResultPedidos);
                } else {
                    response.put('response_x', null);
                }
            } else if (soapAction.contains('wssf_linpedido')) {
                if (requestName == 'CreateMultiple') {
                    AitanaOrderLineWS.CreateMultiple_Result_element createResultLineas = new AitanaOrderLineWS.CreateMultiple_Result_element();
                    createResultLineas.wsSF_LinPedido_List = lineasList;
                    response.put('response_x', createResultLineas);
                } else if (requestName == 'UpdateMultiple') {
                    AitanaOrderLineWS.UpdateMultiple_Result_element updateResultLineas = new AitanaOrderLineWS.UpdateMultiple_Result_element();
                    updateResultLineas.wsSF_LinPedido_List = lineasList;
                    response.put('response_x', updateResultLineas);
                } else if (requestName == 'ReadMultiple') {
                    AitanaOrderLineWS.ReadMultiple_Result_element readResultLineas = new AitanaOrderLineWS.ReadMultiple_Result_element();
                    readResultLineas.ReadMultiple_Result = lineasList;
                    response.put('response_x', readResultLineas);
                } else {
                    response.put('response_x', null);
                }
            }

        }

    }

    public class DireccionMock implements WebServiceMock {

        public void doInvoke(
            Object stub,
            Object request,
            Map<String, Object> response,
            String endpoint,
            String soapAction,
            String requestName,
            String responseNS,
            String responseName,
            String responseType
        ) {
            AitanaDireccionWS.wsSF_DireccionesEnvio direccion = new AitanaDireccionWS.wsSF_DireccionesEnvio();
            direccion.Key = 'test';
            direccion.Code = 'SF00100013'; // IMPORTANTE: AL SER UN AUTONUMBER, ESTE VALOR VA A CAMBIAR. MIRA EN LA DEV CONSOLE DE PRODUCCIÓN, EN DEBUGS HABRÁ UN CÓDIGO SIMILAR.
            direccion.Customer_No = 'test';
            direccion.Name = 'testy';
            direccion.Address = 'test';
            direccion.Address_2 = 'test';
            direccion.City = 'test';
            direccion.Post_Code = 'test';
            direccion.County = 'test';
            direccion.Country_Region_Code = 'test';
            direccion.Dir_envio_principal = true;

            List<AitanaDireccionWS.wsSF_DireccionesEnvio> direcciones = new List<AitanaDireccionWS.wsSF_DireccionesEnvio>();
            direcciones.add(direccion);

            AitanaDireccionWS.wsSF_DireccionesEnvio_List direccionesList = new AitanaDireccionWS.wsSF_DireccionesEnvio_List();
            direccionesList.wsSF_DireccionesEnvio = direcciones;

            if (requestName == 'CreateMultiple') {
                AitanaDireccionWS.CreateMultiple_Result_element createResult = new AitanaDireccionWS.CreateMultiple_Result_element();
                createResult.wsSF_DireccionesEnvio_List = direccionesList;
                response.put('response_x', createResult);
            } else {
                response.put('response_x', null);
            }

        }
    }

    @TestSetup
    static void makeData(){

        TrgController.setDoNotRunTrigger();

        Product2 productTest = new Product2(
            IsActive = true,
            DisplayUrl = 'foto',
            ERUM_External_ProductCode__c = 'no',
            Name = 'name',
            ERUM_Tipo__c = 'Inventario',
            ERUM_Bloqueado__c = false,
            QuantityUnitOfMeasure = 'unidadMedidaVenta',
            ERUM_Cod_categoria_producto__c = 'ALMACEN',
            ERUM_Cod_grupo_producto__c = 'ADZ',
            ERUM_Grupo_prod_Servicio__c = 'GR1',
            ERUM_Material_producto__c = 'PP',
            CurrencyIsoCode = 'EUR',
            ERUM_Volumen__c = 1.0,
            ERUM_Media_percha__c = 1.0,
            ERUM_Ancho_pala__c = 1.0,
            ERUM_Peso_neto__c = 1.0,
            ERUM_Peso_bruto__c = 1.0,
            ERUM_Grupo_contable_producto__c = 'ARANC CV',
            ERUM_Grupo_registro_IVA_prod__c = 'EXENTO',
            ERUM_Grupo_contable_inventario__c = 'ENVASES',
            ProductCode = 'codigoArancelario',
            ERUM_Tipo_palet__c = 'Europeo',
            ERUM_Cantidad_por_palet__c = 1.0,
            ERUM_Stock_disponible__c = 1.0,
            ERUM_Largo_embalaje__c = 1.0,
            ERUM_Ancho_embalaje__c = 1.0,
            ERUM_Alto_embalaje__c = 1.0,
            ERUM_Peso_embalaje__c = 1.0,
            ERUM_Volumen_embalaje__c = 1.0,
            ERUM_Unidad_embalaje__c = 1.0,
            ERUM_Tipo_de_material__c = 'PP',
            ERUM_Peso_neto_cantidad_embalada__c = 1.0,
            ERUM_Peso_bruto_cantidad_embalada__c = 1.0,
            ERUM_Tipo_de_materia_prima__c = 'No procede',
            ERUM_Nivel_tecnoligico__c = 'No procede',
            Family = 'tipoProducto',
            Description = 'descripcionProducto',
            ERUM_Enviada_ERP__c = false,
            Fecha_envio_ERP__c = System.today()
        );
        insert productTest;

        Pricebook2 tarifaTest = new Pricebook2(
            Name = 'nombre',
            Description = 'descripcion',
            IsActive = true,
            ERUM_Moneda__c = 1.0,
            ERUM_Fecha_Inicio__c = System.today(),
            ERUM_Fecha_Final__c = System.today(),
            ERUM_PB_Id_External__c = 'externalId'
        );
        insert tarifaTest;

        PricebookEntry standardEntryTest = new PricebookEntry(
            ERUM_Tipo_de_venta__c = 'Cliente',
            ERUM_Codigo_de_ventas__c = 'cvStandard',
            ERUM_Nombre_codigo_de_ventas__c = 'nombreCVS',
            C_d_Unidad_de_medida__c = 'CAJA',
            UnitPrice = 1.0,
            ERUM_Fecha_Inicial__c = System.today(),
            ERUM_Fecha_Final__c = System.today(),
            ERUM_Incluir_coste_contenedor__c = false,
            CurrencyIsoCode = 'EUR',
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = productTest.Id,
            IsActive = true
        );
        insert standardEntryTest;

        PricebookEntry entryTest = new PricebookEntry(
            ERUM_Tipo_de_venta__c = 'Cliente',
            ERUM_Codigo_de_ventas__c = 'codVentas',
            ERUM_Nombre_codigo_de_ventas__c = 'nombreCV',
            C_d_Unidad_de_medida__c = 'CAJA',
            UnitPrice = 2.0,
            ERUM_Fecha_Inicial__c = System.today(),
            ERUM_Fecha_Final__c = System.today(),
            ERUM_Incluir_coste_contenedor__c = false,
            CurrencyIsoCode = 'EUR',
            Pricebook2Id = tarifaTest.Id,
            Product2Id = productTest.Id,
            IsActive = true
        );
        insert entryTest;

        Id clienteRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente').getRecordTypeId();
        Id pedidoRecordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pedido').getRecordTypeId();

        Account account_x = new Account(
            Name = 'testCuentay cuentaTesty',
            Phone = '12345678',
            RecordTypeId = clienteRecordType,
            ERUM_CIF_Europeo__c = 'test',
            ERUM_Idioma__c = 'ESP',
            ERUM_Estado__c = 'Activo',
            CurrencyIsoCode = 'EUR',
            BillingStreet = 'Calle Cánovas del Castillo, número 12, piso 3, puerta B Derecha',
            BillingPostalCode = '11003',
            BillingCountry = 'ES',
            Num_Exp_CYC__c = '1',
            Fecha_Exp_CYC__c = System.today(),
            Dias_Asegurado_CYC__c = 365,
            Limite_Credito_CYC__c = 125000,
            ERUM_Importe_Concedido__c = 25000,
            ERUM_Activo_ERP__c = true,
            ERUM_Codigo_cliente_ERP__c = 'test0',
            Numero_cliente_ERP__c = 'test',
            ERUM_Fecha_Activo_ERP__c = System.today()
        );

        insert account_x;

        ERUM_Direcciones_Envio__c direccion_x = new ERUM_Direcciones_Envio__c(
            ERUM_Nombre_comercial__c = account_x.Id,
            Name = 'test',
            ERUM_Calle__c = 'Calle Cánovas del Castillo, número 12, piso 3, puerta B Derecha',
            ERUM_Ciudad__c = 'Cádiz',
            ERUM_Codigo_postal__c = '11003',
            ERUM_Pais__c = 'ES',
            ERUM_Country_RegionCOD__c = 'ES',
            ERUM_Direccion_Principal_Envio__c = true,
            ERUM_Activa_ERP__c = true,
            ERUM_Fecha_Activa_ERP__c = System.today(),
            ERUM_Cod_de_Direccion_NAV__c = 'test0'
        );

        insert direccion_x;

        ERUM_Direcciones_Envio__c direccion_y = new ERUM_Direcciones_Envio__c(
            ERUM_Nombre_comercial__c = account_x.Id,
            Name = 'testy',
            ERUM_Calle__c = 'test',
            ERUM_Ciudad__c = 'test',
            ERUM_Codigo_postal__c = 'test',
            ERUM_Pais__c = 'test',
            ERUM_Country_RegionCOD__c = 'test',
            ERUM_Direccion_Principal_Envio__c = true,
            ERUM_Activa_ERP__c = false,
            ERUM_Fecha_Activa_ERP__c = null,
            ERUM_Cod_de_Direccion_NAV__c = null
        );

        insert direccion_y;

        Opportunity opportunity_x = new Opportunity(
            ERUM_Fecha_pedido__c = System.today(),
            ERUM_Nombre_Direccion__c = direccion_x.Id,
            ERUM_Referencia_del_cliente__c = 'test',
            ERUM_Terminos_de_pago__c = '0',
            ERUM_Incoterms__c = 'EXW',
            ERUM_Forma_de_pago__c = 'CONF',
            AccountId = account_x.Id,
            ERUM_Pedido_del_cliente__c = 'test',
            ERUM_Descuento_P_P__c = 10.0,
            RecordTypeId = pedidoRecordType,
            Name = 'testopp1',
            StageName = 'Activo',
            CloseDate = System.today().addYears(1),
            ERUM_Activo_ERP__c = false
        );

        insert opportunity_x;

        Opportunity opportunity_y = new Opportunity(
            ERUM_Fecha_pedido__c = System.today(),
            ERUM_Nombre_Direccion__c = direccion_x.Id,
            ERUM_Referencia_del_cliente__c = 'test',
            ERUM_Terminos_de_pago__c = '0',
            ERUM_Incoterms__c = 'EXW',
            ERUM_Forma_de_pago__c = 'CONF',
            AccountId = account_x.Id,
            ERUM_Pedido_del_cliente__c = 'test',
            ERUM_Descuento_P_P__c = 10.0,
            RecordTypeId = pedidoRecordType,
            Name = 'testopp2',
            StageName = 'Activo',
            CloseDate = System.today().addYears(1),
            ERUM_Activo_ERP__c = true,
            ERUM_Key_Pedido__c = 'test',
            ERUM_Offer_Id_External__c = 'test'
        );

        insert opportunity_y;

        Opportunity opportunity_z = new Opportunity(
            ERUM_Fecha_pedido__c = System.today(),
            ERUM_Nombre_Direccion__c = direccion_x.Id,
            ERUM_Referencia_del_cliente__c = 'test',
            ERUM_Terminos_de_pago__c = '0',
            ERUM_Incoterms__c = 'EXW',
            ERUM_Forma_de_pago__c = 'CONF',
            AccountId = account_x.Id,
            ERUM_Pedido_del_cliente__c = 'test',
            ERUM_Descuento_P_P__c = 10.0,
            RecordTypeId = pedidoRecordType,
            Name = 'testoppz',
            StageName = 'Activo',
            CloseDate = System.today().addYears(1),
            ERUM_Activo_ERP__c = false,
            Pricebook2Id = tarifaTest.Id
        );

        insert opportunity_z;

        OpportunityLineItem line_x = new OpportunityLineItem(
            OpportunityId = opportunity_z.Id,
            Product2Id = productTest.Id,
            TotalPrice = 1.0, 
            ERUM_Impuesto__c = 1.0, 
            Quantity = 1.0, 
            ServiceDate = System.today(), 
            Discount = 1.0, 
            ERUM_UM__c = 'line_x', 
            Description = 'line_x', 
            ERUM_Cantidad_entregada__c = 1.0, 
            ERUM_Activo_ERP__c = false, 
            Erum_Key_Linea__c = 'test', 
            ERUM_Line_No__c = '10000'
        );
        insert line_x;

        OpportunityLineItem line_y = new OpportunityLineItem(
            OpportunityId = opportunity_z.Id,
            Product2Id = productTest.Id,
            TotalPrice = 1.0, 
            ERUM_Impuesto__c = 1.0, 
            Quantity = 1.0, 
            ServiceDate = System.today(), 
            Discount = 1.0, 
            ERUM_UM__c = 'line_y', 
            Description = 'line_y', 
            ERUM_Cantidad_entregada__c = 1.0, 
            ERUM_Activo_ERP__c = true, 
            Erum_Key_Linea__c = 'test', 
            ERUM_Line_No__c = '10000'
        );
        insert line_y;
    }

    /**
     * TESTS TRIGGER ACCOUNT ON INSERT SIN LINEAS E INSERT EN ERP
     */

    @isTest(SeeAllData=false)
    public static void testTrgOpp_1() {
        Id pedidoRecordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pedido').getRecordTypeId();
        Opportunity test1 = new Opportunity(
            ERUM_Fecha_pedido__c = System.today(),
            ERUM_Nombre_Direccion__c = [SELECT Id FROM ERUM_Direcciones_Envio__c WHERE Name =: 'test' LIMIT 1].Id,
            ERUM_Referencia_del_cliente__c = 'test',
            ERUM_Terminos_de_pago__c = '0',
            ERUM_Incoterms__c = 'EXW',
            ERUM_Forma_de_pago__c = 'CONF',
            AccountId = [SELECT Id FROM Account WHERE Name =: 'testCuentay cuentaTesty' LIMIT 1].Id,
            ERUM_Pedido_del_cliente__c = 'test',
            ERUM_Descuento_P_P__c = 10.0,
            RecordTypeId = pedidoRecordType,
            Name = 'testopp1',
            StageName = 'Activo',
            CloseDate = System.today().addYears(1),
            ERUM_Activo_ERP__c = false
        );
        Test.setMock(WebServiceMock.class, new OppMock());
        Test.startTest();
        test1.ERUM_Terminos_de_pago__c = '10';
        Database.insert(test1, true);
        Test.stopTest();
    }
    

    @isTest(SeeAllData=false)
    public static void testWSOpp_1() {
        Opportunity test1 = [
            SELECT ERUM_Fecha_pedido__c, ERUM_Idioma__c, ERUM_Divisa__c, ERUM_Nombre_Direccion__c, ERUM_Referencia_del_cliente__c, ERUM_Terminos_de_pago__c, ERUM_Incoterms__c, ERUM_Forma_de_pago__c, AccountId, ERUM_Pedido_del_cliente__c, ERUM_Descuento_P_P__c, ERUM_Activo_ERP__c
            FROM Opportunity 
            WHERE Name =: 'testopp1'
            LIMIT 1
        ];
        Test.setMock(WebServiceMock.class, new OppMock());
        Test.startTest();
        Map<Id, Opportunity> oppsToInsert = new Map<Id, Opportunity>();
        oppsToInsert.put(test1.Id, test1);
        WSQueueableOpp.QueueableOppInsert job = new WSQueueableOpp.QueueableOppInsert(oppsToInsert, new Map<Id, Opportunity>(), new Map<Id, List<OpportunityLineItem>>(), new Map<Id, List<OpportunityLineItem>>());
        job.execute(null);
        Test.stopTest();
    }

    /**
     * TESTS TRIGGER ACCOUNT ON UPDATE SIN LINEAS Y UPDATE EN ERP
     */

    @isTest(SeeAllData=false)
    public static void testTrgOpp_2() {
        Opportunity test2 = [
            SELECT ERUM_Fecha_pedido__c, ERUM_Idioma__c, ERUM_Divisa__c, ERUM_Nombre_Direccion__c, ERUM_Referencia_del_cliente__c, ERUM_Terminos_de_pago__c, ERUM_Incoterms__c, ERUM_Forma_de_pago__c, AccountId, ERUM_Pedido_del_cliente__c, ERUM_Descuento_P_P__c, ERUM_Key_Pedido__c, ERUM_Offer_Id_External__c, ERUM_Activo_ERP__c
            FROM Opportunity 
            WHERE Name =: 'testopp2'
            LIMIT 1
        ];
        Test.startTest();
        test2.ERUM_Terminos_de_pago__c = '10';
        Database.update(test2, true);
        Test.stopTest();
    }

    @isTest(SeeAllData=false)
    public static void testWSOpp_2() {
        Opportunity test2 = [
            SELECT ERUM_Fecha_pedido__c, ERUM_Idioma__c, ERUM_Divisa__c, ERUM_Nombre_Direccion__c, ERUM_Referencia_del_cliente__c, ERUM_Terminos_de_pago__c, ERUM_Incoterms__c, ERUM_Forma_de_pago__c, AccountId, ERUM_Pedido_del_cliente__c, ERUM_Descuento_P_P__c, ERUM_Key_Pedido__c, ERUM_Offer_Id_External__c, ERUM_Activo_ERP__c
            FROM Opportunity 
            WHERE Name =: 'testopp2'
            LIMIT 1
        ];
        Map<Id, String> oppNos = new Map<Id, String>();
        oppNos.put(test2.Id, 'test2');
        Test.setMock(WebServiceMock.class, new OppMock());
        Test.startTest();
        Map<Id, Opportunity> oppsToUpdate = new Map<Id, Opportunity>();
        oppsToUpdate.put(test2.Id, test2);
        WSQueueableOpp.QueueableOppUpdate job = new WSQueueableOpp.QueueableOppUpdate(oppsToUpdate, new Map<Id, List<OpportunityLineItem>>(), new Map<Id, List<OpportunityLineItem>>(), oppNos);
        job.execute(null);
        Test.stopTest();
    }

    // INSERT EN ERP DE LINEAS
    @isTest(SeeAllData=false)
    public static void testWSLin_1() {
        Opportunity test1 = [
            SELECT Id, ERUM_Fecha_pedido__c, ERUM_Idioma__c, ERUM_Divisa__c, ERUM_Nombre_Direccion__c, ERUM_Referencia_del_cliente__c, ERUM_Terminos_de_pago__c, ERUM_Incoterms__c, ERUM_Forma_de_pago__c, AccountId, ERUM_Pedido_del_cliente__c, ERUM_Descuento_P_P__c, ERUM_Activo_ERP__c
            FROM Opportunity 
            WHERE Name =: 'testoppz'
            LIMIT 1
        ];
        OpportunityLineItem line = [
            SELECT Id, TotalPrice, ERUM_Impuesto__c, ListPrice, ProductCode, Quantity, ServiceDate, Discount, ERUM_UM__c, Description, ERUM_Cantidad_entregada__c, ERUM_Activo_ERP__c, Opportunity.ERUM_Offer_Id_External__c, OpportunityId, Erum_Key_Linea__c, ERUM_Line_No__c, Opportunity.AccountId, Product2.ERUM_External_ProductCode__c
            FROM OpportunityLineItem
            WHERE Description =: 'line_x'
        ];
        Map<Id, String> oppNos = new Map<Id, String>();
        oppNos.put(test1.Id, 'test1');
        List<OpportunityLineItem> lines = new List<OpportunityLineItem>();
        lines.add(line);
        Map<Id, List<OpportunityLineItem>> linesToInsert = new Map<Id, List<OpportunityLineItem>>();
        linesToInsert.put(test1.Id, lines);
        Test.setMock(WebServiceMock.class, new OppMock());
        Test.startTest();
        WSQueableLines.QueueableOpportunityLineInsert job = new WSQueableLines.QueueableOpportunityLineInsert(linesToInsert, new Map<Id, List<OpportunityLineItem>>(), oppNos);
        job.execute(null);
        Test.stopTest();
    }

    // UPDATE EN ERP DE LINEAS
    @isTest(SeeAllData=false)
    public static void testWSLin_2() {
        Opportunity test1 = [
            SELECT Id, ERUM_Fecha_pedido__c, ERUM_Idioma__c, ERUM_Divisa__c, ERUM_Nombre_Direccion__c, ERUM_Referencia_del_cliente__c, ERUM_Terminos_de_pago__c, ERUM_Incoterms__c, ERUM_Forma_de_pago__c, AccountId, ERUM_Pedido_del_cliente__c, ERUM_Descuento_P_P__c, ERUM_Activo_ERP__c
            FROM Opportunity 
            WHERE Name =: 'testoppz'
            LIMIT 1
        ];
        OpportunityLineItem line = [
            SELECT Id, TotalPrice, ERUM_Impuesto__c, ListPrice, ProductCode, Quantity, ServiceDate, Discount, ERUM_UM__c, Description, ERUM_Cantidad_entregada__c, ERUM_Activo_ERP__c, Opportunity.ERUM_Offer_Id_External__c, OpportunityId, Erum_Key_Linea__c, ERUM_Line_No__c, Opportunity.AccountId, Product2.ERUM_External_ProductCode__c
            FROM OpportunityLineItem
            WHERE Description =: 'line_y'
        ];
        List<OpportunityLineItem> lines = new List<OpportunityLineItem>();
        lines.add(line);
        Map<Id, List<OpportunityLineItem>> linesToUpdate = new Map<Id, List<OpportunityLineItem>>();
        linesToUpdate.put(test1.Id, lines);
        Test.setMock(WebServiceMock.class, new OppMock());
        Test.startTest();
        WSQueableLines.QueueableOpportunityLineUpdate job = new WSQueableLines.QueueableOpportunityLineUpdate(linesToUpdate);
        job.execute(null);
        Test.stopTest();
    }

    // UPDATE EN ERP DE DIRECCION
    @isTest(SeeAllData=false)
    public static void testWSDir() {
        ERUM_Direcciones_Envio__c direccion_y = [
            SELECT ERUM_Nombre_comercial__c, Name, ERUM_Calle__c, ERUM_Ciudad__c, ERUM_Codigo_postal__c, ERUM_Pais__c, ERUM_Country_RegionCOD__c, ERUM_Direccion_Principal_Envio__c, ERUM_Activa_ERP__c, ERUM_Fecha_Activa_ERP__c, ERUM_Cod_de_Direccion_NAV__c
            FROM ERUM_Direcciones_Envio__c
            WHERE Name =: 'testy'
            LIMIT 1
        ];
        Test.setMock(WebServiceMock.class, new DireccionMock());
        Test.startTest();
        Map<Id, ERUM_Direcciones_Envio__c> dirsToInsert = new Map<Id, ERUM_Direcciones_Envio__c>();
        dirsToInsert.put(direccion_y.Id, direccion_y);
        WSQueueableOpp.QueueableDireccionInsert job = new WSQueueableOpp.QueueableDireccionInsert(dirsToInsert, new Map<Id, Opportunity>(), new Map<Id, Opportunity>(), new Map<Id, List<OpportunityLineItem>>(), new Map<Id, List<OpportunityLineItem>>());
        job.execute(null);
        Test.stopTest();
    }

}